[print_config]
dir_color = "cyan"
file_color = ""
symbol_color = "bright green"
tree_color = ""
grep_pass_color = "bright green"
grep_match_color = "bright red"

[path_config]
default_repo = "<Your Home>/.password-store"
repos = ["<Your Home>/.password-store"]

[executable_config]
pgp_executable = "gpg2"
editor_executable = "notepad"
git_executable = "git"

[feature_config]
clip_time = 45
fuzzy_search = true
