[package]
name = "pars-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
pass-store-rs-core = { path = "../core" }

[profile.release]
lto = "fat"
opt-level = "z"

[[bin]]
name = "pars"
path ="src/main.rs"
