// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_canonical_store`, `clone_git_repository`, `clone_store_inner`, `configure_pgp_backend_inner`, `configured_upstream`, `create_local_store_inner`, `create_new_store_tree`, `default_ssh_dir`, `delete_local_store_inner`, `disconnect_store_inner`, `entry_ref`, `export_pgp_private_key_inner`, `git_failure`, `git_remote_callbacks`, `import_local_store_inner`, `imported_key_kind`, `init_git_repository`, `initialize_store_recipients_inner`, `inspect_app_state_inner`, `inspect_git_mode`, `inspect_store`, `legacy_import_pgp_key_text`, `legacy_key_mutation_response`, `lifecycle_state`, `list_keys_inner`, `load_config_copy`, `load_config_for_mutation`, `normalize_store_root`, `normalized_keys`, `pgp_backend`, `pgp_import_source_label`, `pgp_key_identity_for_confirmation`, `pgp_key_import_response`, `pgp_key_matches`, `pgp_key_missing`, `pgp_key_record`, `pgp_preparation_failure`, `read_entry_inner`, `read_regular_gpg_id`, `rename_directory_noreplace`, `require_app_managed_root`, `require_canonical_store`, `require_empty_canonical_store`, `required_remote_url`, `run_git_command_response_owned`, `run_git_command_response`, `run_system_git`, `sanitize_git_text`, `sanitize_git_token`, `sanitized_remote_url`, `save_config_for_mutation`, `set_canonical_store`, `simple`, `status_code`, `store_failure`, `store_name`, `structured_git_commit`, `structured_git_list_remotes`, `structured_git_pull`, `structured_git_push`, `structured_git_remote_mutation`, `structured_git_response`, `structured_git_status`, `structured_or_system_remote_response`, `validated_recipients`, `write_new_gpg_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AddPgpKeyToGpgIdRequest`, `ConfiguredUpstream`, `DeletePgpKeyRequest`, `DeletePgpKeyResponse`, `ExportPgpKeyRequest`, `GitRemoteMutation`, `PgpKeyDeletionFailureKind`, `PgpKeyDeletionResultDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `add_pgp_key_to_gpg_id`, `delete_pgp_key`, `export_pgp_private_key`, `export_pgp_public_key`, `import_pgp_private_key_file`, `import_pgp_private_key_text`, `import_pgp_public_key`

Future<ConfigResponse> loadConfig({required LoadConfigRequest request}) =>
    RustLib.instance.api.crateApiLoadConfig(request: request);

Future<UnitResponse> saveConfig({required SaveConfigRequest request}) =>
    RustLib.instance.api.crateApiSaveConfig(request: request);

Future<UnitResponse> configurePgpBackend({
  required ConfigurePgpBackendRequest request,
}) => RustLib.instance.api.crateApiConfigurePgpBackend(request: request);

Future<ListEntriesResponse> listEntries({
  required ListEntriesRequest request,
}) => RustLib.instance.api.crateApiListEntries(request: request);

Future<EntrySecretResponse> readEntry({required EntryRequest request}) =>
    RustLib.instance.api.crateApiReadEntry(request: request);

Future<CopyEntryPasswordResponse> copyEntryPassword({
  required EntryRequest request,
}) => RustLib.instance.api.crateApiCopyEntryPassword(request: request);

Future<UnitResponse> rebuildAutofillIndex({
  required RebuildAutofillIndexRequest request,
}) => RustLib.instance.api.crateApiRebuildAutofillIndex(request: request);

Future<UnitResponse> upsertAutofillIndexEntry({
  required UpsertAutofillIndexEntryRequest request,
}) => RustLib.instance.api.crateApiUpsertAutofillIndexEntry(request: request);

Future<UnitResponse> moveAutofillIndexEntry({
  required MoveAutofillIndexEntryRequest request,
}) => RustLib.instance.api.crateApiMoveAutofillIndexEntry(request: request);

Future<UnitResponse> removeAutofillIndexEntry({
  required RemoveAutofillIndexEntryRequest request,
}) => RustLib.instance.api.crateApiRemoveAutofillIndexEntry(request: request);

Future<UnitResponse> patchAutofillIndexFavorites({
  required PatchAutofillIndexFavoritesRequest request,
}) =>
    RustLib.instance.api.crateApiPatchAutofillIndexFavorites(request: request);

Future<UnitResponse> reconcileAutofillIndex({
  required ReconcileAutofillIndexRequest request,
}) => RustLib.instance.api.crateApiReconcileAutofillIndex(request: request);

Future<UnitResponse> enrichAutofillIndexWebsites({
  required EnrichAutofillIndexWebsitesRequest request,
}) =>
    RustLib.instance.api.crateApiEnrichAutofillIndexWebsites(request: request);

Future<UnitResponse> clearAutofillIndexWebsites({
  required ClearAutofillIndexWebsitesRequest request,
}) => RustLib.instance.api.crateApiClearAutofillIndexWebsites(request: request);

Future<AutofillCandidatesResponse> queryAutofillCandidates({
  required AutofillQueryRequest request,
}) => RustLib.instance.api.crateApiQueryAutofillCandidates(request: request);

Future<AutofillCredentialResponse> resolveAutofillCredential({
  required AutofillCredentialRequest request,
}) => RustLib.instance.api.crateApiResolveAutofillCredential(request: request);

Future<UnitResponse> clearAutofillIndex({
  required ClearAutofillIndexRequest request,
}) => RustLib.instance.api.crateApiClearAutofillIndex(request: request);

Future<InsertEntryResponse> insertEntry({
  required InsertEntryRequest request,
}) => RustLib.instance.api.crateApiInsertEntry(request: request);

Future<GenerateEntryResponse> generateEntry({
  required GenerateEntryRequest request,
}) => RustLib.instance.api.crateApiGenerateEntry(request: request);

Future<MutationResponse> editEntry({required EditEntryRequest request}) =>
    RustLib.instance.api.crateApiEditEntry(request: request);

Future<MutationResponse> moveEntry({required MoveEntryRequest request}) =>
    RustLib.instance.api.crateApiMoveEntry(request: request);

Future<DeleteEntryResponse> deleteEntry({
  required DeleteEntryRequest request,
}) => RustLib.instance.api.crateApiDeleteEntry(request: request);

Future<GitCommandResponse> gitStatus({required GitRequest request}) =>
    RustLib.instance.api.crateApiGitStatus(request: request);

Future<GitCommandResponse> gitPull({required GitRequest request}) =>
    RustLib.instance.api.crateApiGitPull(request: request);

Future<GitCommandResponse> gitPush({required GitRequest request}) =>
    RustLib.instance.api.crateApiGitPush(request: request);

Future<GitCommandResponse> gitCommit({required GitCommitRequest request}) =>
    RustLib.instance.api.crateApiGitCommit(request: request);

Future<GitCommandResponse> gitListRemotes({required GitRequest request}) =>
    RustLib.instance.api.crateApiGitListRemotes(request: request);

Future<GitCommandResponse> gitAddRemote({required GitRemoteRequest request}) =>
    RustLib.instance.api.crateApiGitAddRemote(request: request);

Future<GitCommandResponse> gitSetRemoteUrl({
  required GitRemoteRequest request,
}) => RustLib.instance.api.crateApiGitSetRemoteUrl(request: request);

Future<GitCommandResponse> gitRemoveRemote({
  required GitRemoteRequest request,
}) => RustLib.instance.api.crateApiGitRemoveRemote(request: request);

Future<GitCommandResponse> runGitArgs({required GitArgsRequest request}) =>
    RustLib.instance.api.crateApiRunGitArgs(request: request);

Future<InspectStoreGitResponse> inspectStoreGit({
  required InspectStoreGitRequest request,
}) => RustLib.instance.api.crateApiInspectStoreGit(request: request);

Future<UnitResponse> initializeGitRepository({
  required InitializeGitRepositoryRequest request,
}) => RustLib.instance.api.crateApiInitializeGitRepository(request: request);

Future<AppStateResponse> inspectAppState({
  required InspectAppStateRequest request,
}) => RustLib.instance.api.crateApiInspectAppState(request: request);

Future<UnitResponse> createLocalStore({
  required CreateLocalStoreRequest request,
}) => RustLib.instance.api.crateApiCreateLocalStore(request: request);

Future<UnitResponse> importLocalStore({
  required ImportLocalStoreRequest request,
}) => RustLib.instance.api.crateApiImportLocalStore(request: request);

Future<UnitResponse> cloneStore({required CloneStoreRequest request}) =>
    RustLib.instance.api.crateApiCloneStore(request: request);

Future<UnitResponse> disconnectStore({
  required DisconnectStoreRequest request,
}) => RustLib.instance.api.crateApiDisconnectStore(request: request);

Future<UnitResponse> deleteLocalStore({
  required DeleteLocalStoreRequest request,
}) => RustLib.instance.api.crateApiDeleteLocalStore(request: request);

Future<ListKeysResponse> listKeys({required ListKeysRequest request}) =>
    RustLib.instance.api.crateApiListKeys(request: request);

Future<KeyDetectionResponse> detectImportedKey({
  required ImportKeyTextRequest request,
}) => RustLib.instance.api.crateApiDetectImportedKey(request: request);

Future<KeyMutationResponse> generatePgpKey({
  required GeneratePgpKeyRequest request,
}) => RustLib.instance.api.crateApiGeneratePgpKey(request: request);

/// Inspects pasted PGP key material without touching any keyring.
Future<PgpKeyInspectionResponse> inspectPgpKeyText({
  required InspectPgpKeyTextRequest request,
}) => RustLib.instance.api.crateApiInspectPgpKeyText(request: request);

/// Inspects a local key file. The file's bytes are read here and never returned to Flutter.
Future<PgpKeyInspectionResponse> inspectPgpKeyFile({
  required InspectPgpKeyFileRequest request,
}) => RustLib.instance.api.crateApiInspectPgpKeyFile(request: request);

/// Imports pasted PGP key material of either kind, validating any passphrase before mutating.
Future<PgpKeyImportResponse> importPgpKeyText({
  required ImportPgpKeyTextRequest request,
}) => RustLib.instance.api.crateApiImportPgpKeyText(request: request);

/// Imports a PGP key file of either kind. Binary exports are supported because the file is read as
/// bytes rather than UTF-8 text.
Future<PgpKeyImportResponse> importPgpKeyFile({
  required ImportPgpKeyFileRequest request,
}) => RustLib.instance.api.crateApiImportPgpKeyFile(request: request);

Future<PreparePgpPrivateKeyResponse> preparePgpPrivateKey({
  required PreparePgpPrivateKeyRequest request,
}) => RustLib.instance.api.crateApiPreparePgpPrivateKey(request: request);

Future<UnitResponse> initializeStoreRecipients({
  required InitializeStoreRecipientsRequest request,
}) => RustLib.instance.api.crateApiInitializeStoreRecipients(request: request);

Future<KeyMutationResponse> generateSshKey({
  required GenerateSshKeyRequest request,
}) => RustLib.instance.api.crateApiGenerateSshKey(request: request);

Future<KeyMutationResponse> importSshPrivateKeyText({
  required ImportKeyTextRequest request,
}) => RustLib.instance.api.crateApiImportSshPrivateKeyText(request: request);

Future<KeyMutationResponse> importSshPrivateKeyFile({
  required ImportKeyFileRequest request,
}) => RustLib.instance.api.crateApiImportSshPrivateKeyFile(request: request);

Future<KeyExportResponse> exportSshPublicKey({
  required ExportSshKeyRequest request,
}) => RustLib.instance.api.crateApiExportSshPublicKey(request: request);

Future<KeyExportResponse> exportSshPrivateKey({
  required ExportSshKeyRequest request,
}) => RustLib.instance.api.crateApiExportSshPrivateKey(request: request);

Future<UnitResponse> deleteSshKey({required DeleteSshKeyRequest request}) =>
    RustLib.instance.api.crateApiDeleteSshKey(request: request);

Future<OpenExternalUrlResponse> openGithubSshSettings({
  required OpenGithubSshSettingsRequest request,
}) => RustLib.instance.api.crateApiOpenGithubSshSettings(request: request);

class AppStateDto {
  final String configPath;
  final bool configExists;
  final String onboardingState;
  final List<String> issues;
  final StoreStatusDto? store;

  const AppStateDto({
    required this.configPath,
    required this.configExists,
    required this.onboardingState,
    required this.issues,
    this.store,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      configExists.hashCode ^
      onboardingState.hashCode ^
      issues.hashCode ^
      store.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStateDto &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          configExists == other.configExists &&
          onboardingState == other.onboardingState &&
          issues == other.issues &&
          store == other.store;
}

class AppStateResponse {
  final AppStateDto? state;
  final BridgeFailure? error;

  const AppStateResponse({this.state, this.error});

  @override
  int get hashCode => state.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStateResponse &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          error == other.error;
}

class AutofillCandidateDto {
  final String path;
  final String displayName;
  final String username;
  final String matchKind;
  final String matchValue;
  final int score;
  final bool isFavorite;

  const AutofillCandidateDto({
    required this.path,
    required this.displayName,
    required this.username,
    required this.matchKind,
    required this.matchValue,
    required this.score,
    required this.isFavorite,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      displayName.hashCode ^
      username.hashCode ^
      matchKind.hashCode ^
      matchValue.hashCode ^
      score.hashCode ^
      isFavorite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillCandidateDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          displayName == other.displayName &&
          username == other.username &&
          matchKind == other.matchKind &&
          matchValue == other.matchValue &&
          score == other.score &&
          isFavorite == other.isFavorite;
}

class AutofillCandidatesResponse {
  final List<AutofillCandidateDto> candidates;
  final BridgeFailure? error;

  const AutofillCandidatesResponse({required this.candidates, this.error});

  @override
  int get hashCode => candidates.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillCandidatesResponse &&
          runtimeType == other.runtimeType &&
          candidates == other.candidates &&
          error == other.error;
}

class AutofillCredentialDto {
  final String path;
  final String username;
  final String password;

  const AutofillCredentialDto({
    required this.path,
    required this.username,
    required this.password,
  });

  @override
  int get hashCode => path.hashCode ^ username.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillCredentialDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          username == other.username &&
          password == other.password;
}

class AutofillCredentialRequest {
  final String configPath;
  final String indexPath;
  final String root;
  final String path;
  final String? pgpExecutable;
  final String? passphrase;

  const AutofillCredentialRequest({
    required this.configPath,
    required this.indexPath,
    required this.root,
    required this.path,
    this.pgpExecutable,
    this.passphrase,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      indexPath.hashCode ^
      root.hashCode ^
      path.hashCode ^
      pgpExecutable.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillCredentialRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          indexPath == other.indexPath &&
          root == other.root &&
          path == other.path &&
          pgpExecutable == other.pgpExecutable &&
          passphrase == other.passphrase;
}

class AutofillCredentialResponse {
  final AutofillCredentialDto? credential;
  final BridgeFailure? error;

  const AutofillCredentialResponse({this.credential, this.error});

  @override
  int get hashCode => credential.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillCredentialResponse &&
          runtimeType == other.runtimeType &&
          credential == other.credential &&
          error == other.error;
}

class AutofillEntryMetadataDto {
  final String path;
  final bool isFavorite;

  const AutofillEntryMetadataDto({
    required this.path,
    required this.isFavorite,
  });

  @override
  int get hashCode => path.hashCode ^ isFavorite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillEntryMetadataDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          isFavorite == other.isFavorite;
}

class AutofillQueryRequest {
  final String indexPath;
  final String? website;
  final String? appName;
  final String? query;
  final int limit;

  const AutofillQueryRequest({
    required this.indexPath,
    this.website,
    this.appName,
    this.query,
    required this.limit,
  });

  @override
  int get hashCode =>
      indexPath.hashCode ^
      website.hashCode ^
      appName.hashCode ^
      query.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutofillQueryRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          website == other.website &&
          appName == other.appName &&
          query == other.query &&
          limit == other.limit;
}

class BridgeFailure {
  final BridgeFailureCategory category;
  final String message;
  final String? conflictKind;
  final String? path;

  /// Set only for PGP import failures, so Flutter can branch on the reason rather than the text.
  final PgpImportFailureKind? pgpImportKind;

  const BridgeFailure({
    required this.category,
    required this.message,
    this.conflictKind,
    this.path,
    this.pgpImportKind,
  });

  @override
  int get hashCode =>
      category.hashCode ^
      message.hashCode ^
      conflictKind.hashCode ^
      path.hashCode ^
      pgpImportKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFailure &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          message == other.message &&
          conflictKind == other.conflictKind &&
          path == other.path &&
          pgpImportKind == other.pgpImportKind;
}

enum BridgeFailureCategory {
  configError,
  storeError,
  pgpError,
  gitError,
  clipboardError,
  validationError,
  conflict,
  unsupportedPlatform,
}

class ClearAutofillIndexRequest {
  final String indexPath;

  const ClearAutofillIndexRequest({required this.indexPath});

  @override
  int get hashCode => indexPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClearAutofillIndexRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath;
}

class ClearAutofillIndexWebsitesRequest {
  final String indexPath;
  final List<String> paths;

  const ClearAutofillIndexWebsitesRequest({
    required this.indexPath,
    required this.paths,
  });

  @override
  int get hashCode => indexPath.hashCode ^ paths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClearAutofillIndexWebsitesRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          paths == other.paths;
}

class CloneStoreRequest {
  final String configPath;
  final String remoteUrl;
  final String root;
  final String? sshPrivateKeyPath;
  final String? sshDir;

  const CloneStoreRequest({
    required this.configPath,
    required this.remoteUrl,
    required this.root,
    this.sshPrivateKeyPath,
    this.sshDir,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      remoteUrl.hashCode ^
      root.hashCode ^
      sshPrivateKeyPath.hashCode ^
      sshDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloneStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          remoteUrl == other.remoteUrl &&
          root == other.root &&
          sshPrivateKeyPath == other.sshPrivateKeyPath &&
          sshDir == other.sshDir;
}

class ConfigResponse {
  final String? configToml;
  final BridgeFailure? error;

  const ConfigResponse({this.configToml, this.error});

  @override
  int get hashCode => configToml.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigResponse &&
          runtimeType == other.runtimeType &&
          configToml == other.configToml &&
          error == other.error;
}

class ConfigurePgpBackendRequest {
  final String configPath;
  final String backend;
  final String? keyringHome;
  final String? pgpExecutable;

  const ConfigurePgpBackendRequest({
    required this.configPath,
    required this.backend,
    this.keyringHome,
    this.pgpExecutable,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      backend.hashCode ^
      keyringHome.hashCode ^
      pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigurePgpBackendRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          backend == other.backend &&
          keyringHome == other.keyringHome &&
          pgpExecutable == other.pgpExecutable;
}

class CopyEntryPasswordResponse {
  final CopyEntryPasswordResult? result;
  final BridgeFailure? error;

  const CopyEntryPasswordResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopyEntryPasswordResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class CopyEntryPasswordResult {
  final String path;
  final String password;

  const CopyEntryPasswordResult({required this.path, required this.password});

  @override
  int get hashCode => path.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopyEntryPasswordResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          password == other.password;
}

class CreateLocalStoreRequest {
  final String configPath;
  final String name;
  final String root;
  final List<String> pgpKeys;
  final bool initializeGit;

  const CreateLocalStoreRequest({
    required this.configPath,
    required this.name,
    required this.root,
    required this.pgpKeys,
    required this.initializeGit,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      name.hashCode ^
      root.hashCode ^
      pgpKeys.hashCode ^
      initializeGit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateLocalStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          name == other.name &&
          root == other.root &&
          pgpKeys == other.pgpKeys &&
          initializeGit == other.initializeGit;
}

class DeleteEntryRequest {
  final String root;
  final String path;
  final bool recursive;

  const DeleteEntryRequest({
    required this.root,
    required this.path,
    required this.recursive,
  });

  @override
  int get hashCode => root.hashCode ^ path.hashCode ^ recursive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteEntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          path == other.path &&
          recursive == other.recursive;
}

class DeleteEntryResponse {
  final DeleteEntryResultDto? result;
  final BridgeFailure? error;

  const DeleteEntryResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteEntryResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class DeleteEntryResultDto {
  final String deletedPath;
  final String deletedType;

  const DeleteEntryResultDto({
    required this.deletedPath,
    required this.deletedType,
  });

  @override
  int get hashCode => deletedPath.hashCode ^ deletedType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteEntryResultDto &&
          runtimeType == other.runtimeType &&
          deletedPath == other.deletedPath &&
          deletedType == other.deletedType;
}

class DeleteLocalStoreRequest {
  final String configPath;
  final String root;
  final String managedStoreBase;
  final String confirmation;

  const DeleteLocalStoreRequest({
    required this.configPath,
    required this.root,
    required this.managedStoreBase,
    required this.confirmation,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      root.hashCode ^
      managedStoreBase.hashCode ^
      confirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteLocalStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          managedStoreBase == other.managedStoreBase &&
          confirmation == other.confirmation;
}

class DeleteSshKeyRequest {
  final String sshDir;
  final String name;

  const DeleteSshKeyRequest({required this.sshDir, required this.name});

  @override
  int get hashCode => sshDir.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteSshKeyRequest &&
          runtimeType == other.runtimeType &&
          sshDir == other.sshDir &&
          name == other.name;
}

class DisconnectStoreRequest {
  final String configPath;
  final String root;

  const DisconnectStoreRequest({required this.configPath, required this.root});

  @override
  int get hashCode => configPath.hashCode ^ root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisconnectStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root;
}

class EditEntryRequest {
  final String configPath;
  final String root;
  final String path;
  final String content;
  final String pgpExecutable;

  const EditEntryRequest({
    required this.configPath,
    required this.root,
    required this.path,
    required this.content,
    required this.pgpExecutable,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      root.hashCode ^
      path.hashCode ^
      content.hashCode ^
      pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditEntryRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          path == other.path &&
          content == other.content &&
          pgpExecutable == other.pgpExecutable;
}

class EnrichAutofillIndexWebsitesRequest {
  final String configPath;
  final String indexPath;
  final String root;
  final String? pgpExecutable;
  final String? passphrase;
  final List<String> paths;

  const EnrichAutofillIndexWebsitesRequest({
    required this.configPath,
    required this.indexPath,
    required this.root,
    this.pgpExecutable,
    this.passphrase,
    required this.paths,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      indexPath.hashCode ^
      root.hashCode ^
      pgpExecutable.hashCode ^
      passphrase.hashCode ^
      paths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrichAutofillIndexWebsitesRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          indexPath == other.indexPath &&
          root == other.root &&
          pgpExecutable == other.pgpExecutable &&
          passphrase == other.passphrase &&
          paths == other.paths;
}

class EntryRequest {
  final String configPath;
  final String root;
  final String path;
  final String? pgpExecutable;
  final String? passphrase;

  const EntryRequest({
    required this.configPath,
    required this.root,
    required this.path,
    this.pgpExecutable,
    this.passphrase,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      root.hashCode ^
      path.hashCode ^
      pgpExecutable.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          path == other.path &&
          pgpExecutable == other.pgpExecutable &&
          passphrase == other.passphrase;
}

class EntrySecretDto {
  final String password;
  final List<ParsedEntryFieldDto> fields;
  final String rawNotes;

  const EntrySecretDto({
    required this.password,
    required this.fields,
    required this.rawNotes,
  });

  @override
  int get hashCode => password.hashCode ^ fields.hashCode ^ rawNotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySecretDto &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          fields == other.fields &&
          rawNotes == other.rawNotes;
}

class EntrySecretResponse {
  final EntrySecretDto? secret;
  final BridgeFailure? error;

  const EntrySecretResponse({this.secret, this.error});

  @override
  int get hashCode => secret.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySecretResponse &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          error == other.error;
}

class EntrySummaryDto {
  final String path;
  final String name;
  final String? parentPath;
  final String entryType;
  final int childCount;

  const EntrySummaryDto({
    required this.path,
    required this.name,
    this.parentPath,
    required this.entryType,
    required this.childCount,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      parentPath.hashCode ^
      entryType.hashCode ^
      childCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySummaryDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          parentPath == other.parentPath &&
          entryType == other.entryType &&
          childCount == other.childCount;
}

class ExportSshKeyRequest {
  final String sshDir;
  final String name;
  final String? confirmation;

  const ExportSshKeyRequest({
    required this.sshDir,
    required this.name,
    this.confirmation,
  });

  @override
  int get hashCode => sshDir.hashCode ^ name.hashCode ^ confirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportSshKeyRequest &&
          runtimeType == other.runtimeType &&
          sshDir == other.sshDir &&
          name == other.name &&
          confirmation == other.confirmation;
}

class GenerateEntryRequest {
  final String configPath;
  final String root;
  final String path;
  final int length;
  final bool noSymbols;
  final bool overwrite;
  final String pgpExecutable;

  const GenerateEntryRequest({
    required this.configPath,
    required this.root,
    required this.path,
    required this.length,
    required this.noSymbols,
    required this.overwrite,
    required this.pgpExecutable,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      root.hashCode ^
      path.hashCode ^
      length.hashCode ^
      noSymbols.hashCode ^
      overwrite.hashCode ^
      pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateEntryRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          path == other.path &&
          length == other.length &&
          noSymbols == other.noSymbols &&
          overwrite == other.overwrite &&
          pgpExecutable == other.pgpExecutable;
}

class GenerateEntryResponse {
  final GenerateEntryResultDto? result;
  final BridgeFailure? error;

  const GenerateEntryResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateEntryResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class GenerateEntryResultDto {
  final String entryPath;
  final String password;
  final bool overwroteExisting;

  const GenerateEntryResultDto({
    required this.entryPath,
    required this.password,
    required this.overwroteExisting,
  });

  @override
  int get hashCode =>
      entryPath.hashCode ^ password.hashCode ^ overwroteExisting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateEntryResultDto &&
          runtimeType == other.runtimeType &&
          entryPath == other.entryPath &&
          password == other.password &&
          overwroteExisting == other.overwroteExisting;
}

class GeneratePgpKeyRequest {
  final String configPath;
  final String? pgpExecutable;
  final String name;
  final String email;
  final String? passphrase;

  const GeneratePgpKeyRequest({
    required this.configPath,
    this.pgpExecutable,
    required this.name,
    required this.email,
    this.passphrase,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      name.hashCode ^
      email.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratePgpKeyRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          name == other.name &&
          email == other.email &&
          passphrase == other.passphrase;
}

class GenerateSshKeyRequest {
  final String sshDir;
  final String name;

  const GenerateSshKeyRequest({required this.sshDir, required this.name});

  @override
  int get hashCode => sshDir.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateSshKeyRequest &&
          runtimeType == other.runtimeType &&
          sshDir == other.sshDir &&
          name == other.name;
}

class GitArgsRequest {
  final String root;
  final List<String> args;

  const GitArgsRequest({required this.root, required this.args});

  @override
  int get hashCode => root.hashCode ^ args.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitArgsRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          args == other.args;
}

class GitCommandOutputDto {
  final String command;
  final String stdout;
  final String stderr;
  final int? exitCode;
  final bool success;

  const GitCommandOutputDto({
    required this.command,
    required this.stdout,
    required this.stderr,
    this.exitCode,
    required this.success,
  });

  @override
  int get hashCode =>
      command.hashCode ^
      stdout.hashCode ^
      stderr.hashCode ^
      exitCode.hashCode ^
      success.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommandOutputDto &&
          runtimeType == other.runtimeType &&
          command == other.command &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          exitCode == other.exitCode &&
          success == other.success;
}

class GitCommandResponse {
  final GitCommandOutputDto? output;
  final BridgeFailure? error;

  const GitCommandResponse({this.output, this.error});

  @override
  int get hashCode => output.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommandResponse &&
          runtimeType == other.runtimeType &&
          output == other.output &&
          error == other.error;
}

class GitCommitRequest {
  final String root;
  final String message;

  const GitCommitRequest({required this.root, required this.message});

  @override
  int get hashCode => root.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommitRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          message == other.message;
}

class GitRemoteRequest {
  final String root;
  final String name;
  final String? url;

  const GitRemoteRequest({required this.root, required this.name, this.url});

  @override
  int get hashCode => root.hashCode ^ name.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRemoteRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          name == other.name &&
          url == other.url;
}

class GitRequest {
  final String root;
  final String? sshPrivateKeyPath;
  final String? sshDir;

  const GitRequest({required this.root, this.sshPrivateKeyPath, this.sshDir});

  @override
  int get hashCode =>
      root.hashCode ^ sshPrivateKeyPath.hashCode ^ sshDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          sshPrivateKeyPath == other.sshPrivateKeyPath &&
          sshDir == other.sshDir;
}

class ImportKeyFileRequest {
  final String configPath;
  final String? pgpExecutable;
  final String? sshDir;
  final String? name;
  final String path;

  const ImportKeyFileRequest({
    required this.configPath,
    this.pgpExecutable,
    this.sshDir,
    this.name,
    required this.path,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      sshDir.hashCode ^
      name.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportKeyFileRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          sshDir == other.sshDir &&
          name == other.name &&
          path == other.path;
}

class ImportKeyTextRequest {
  final String configPath;
  final String? pgpExecutable;
  final String? sshDir;
  final String? name;
  final String armoredText;

  const ImportKeyTextRequest({
    required this.configPath,
    this.pgpExecutable,
    this.sshDir,
    this.name,
    required this.armoredText,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      sshDir.hashCode ^
      name.hashCode ^
      armoredText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportKeyTextRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          sshDir == other.sshDir &&
          name == other.name &&
          armoredText == other.armoredText;
}

class ImportLocalStoreRequest {
  final String configPath;
  final String root;

  const ImportLocalStoreRequest({required this.configPath, required this.root});

  @override
  int get hashCode => configPath.hashCode ^ root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportLocalStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root;
}

class ImportPgpKeyFileRequest {
  final String configPath;
  final String? pgpExecutable;
  final String path;

  /// Required only when inspection reports `requires_passphrase`.
  final String? passphrase;

  const ImportPgpKeyFileRequest({
    required this.configPath,
    this.pgpExecutable,
    required this.path,
    this.passphrase,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      path.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportPgpKeyFileRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          path == other.path &&
          passphrase == other.passphrase;
}

class ImportPgpKeyTextRequest {
  final String configPath;
  final String? pgpExecutable;
  final String armoredText;

  /// Required only when inspection reports `requires_passphrase`.
  final String? passphrase;

  const ImportPgpKeyTextRequest({
    required this.configPath,
    this.pgpExecutable,
    required this.armoredText,
    this.passphrase,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      armoredText.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportPgpKeyTextRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          armoredText == other.armoredText &&
          passphrase == other.passphrase;
}

class InitializeGitRepositoryRequest {
  final String root;

  const InitializeGitRepositoryRequest({required this.root});

  @override
  int get hashCode => root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitializeGitRepositoryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root;
}

class InitializeStoreRecipientsRequest {
  final String configPath;
  final String root;
  final List<String> fingerprints;

  const InitializeStoreRecipientsRequest({
    required this.configPath,
    required this.root,
    required this.fingerprints,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^ root.hashCode ^ fingerprints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitializeStoreRecipientsRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          fingerprints == other.fingerprints;
}

class InsertEntryRequest {
  final String configPath;
  final String root;
  final String path;
  final String content;
  final bool overwrite;
  final String pgpExecutable;

  const InsertEntryRequest({
    required this.configPath,
    required this.root,
    required this.path,
    required this.content,
    required this.overwrite,
    required this.pgpExecutable,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      root.hashCode ^
      path.hashCode ^
      content.hashCode ^
      overwrite.hashCode ^
      pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertEntryRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          path == other.path &&
          content == other.content &&
          overwrite == other.overwrite &&
          pgpExecutable == other.pgpExecutable;
}

class InsertEntryResponse {
  final InsertEntryResultDto? result;
  final BridgeFailure? error;

  const InsertEntryResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertEntryResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class InsertEntryResultDto {
  final String entryPath;
  final bool overwroteExisting;

  const InsertEntryResultDto({
    required this.entryPath,
    required this.overwroteExisting,
  });

  @override
  int get hashCode => entryPath.hashCode ^ overwroteExisting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertEntryResultDto &&
          runtimeType == other.runtimeType &&
          entryPath == other.entryPath &&
          overwroteExisting == other.overwroteExisting;
}

class InspectAppStateRequest {
  final String configPath;
  final String? pgpExecutable;

  const InspectAppStateRequest({required this.configPath, this.pgpExecutable});

  @override
  int get hashCode => configPath.hashCode ^ pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectAppStateRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable;
}

class InspectPgpKeyFileRequest {
  final String path;

  const InspectPgpKeyFileRequest({required this.path});

  @override
  int get hashCode => path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectPgpKeyFileRequest &&
          runtimeType == other.runtimeType &&
          path == other.path;
}

class InspectPgpKeyTextRequest {
  final String armoredText;

  const InspectPgpKeyTextRequest({required this.armoredText});

  @override
  int get hashCode => armoredText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectPgpKeyTextRequest &&
          runtimeType == other.runtimeType &&
          armoredText == other.armoredText;
}

class InspectStoreGitRequest {
  final String root;

  const InspectStoreGitRequest({required this.root});

  @override
  int get hashCode => root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectStoreGitRequest &&
          runtimeType == other.runtimeType &&
          root == other.root;
}

class InspectStoreGitResponse {
  final StoreGitModeDto? mode;
  final BridgeFailure? error;

  const InspectStoreGitResponse({this.mode, this.error});

  @override
  int get hashCode => mode.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectStoreGitResponse &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          error == other.error;
}

class KeyDetectionResponse {
  final String? kind;
  final BridgeFailure? error;

  const KeyDetectionResponse({this.kind, this.error});

  @override
  int get hashCode => kind.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyDetectionResponse &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          error == other.error;
}

class KeyExportDto {
  final String armoredText;

  const KeyExportDto({required this.armoredText});

  @override
  int get hashCode => armoredText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyExportDto &&
          runtimeType == other.runtimeType &&
          armoredText == other.armoredText;
}

class KeyExportResponse {
  final KeyExportDto? export_;
  final BridgeFailure? error;

  const KeyExportResponse({this.export_, this.error});

  @override
  int get hashCode => export_.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyExportResponse &&
          runtimeType == other.runtimeType &&
          export_ == other.export_ &&
          error == other.error;
}

class KeyMutationResponse {
  final KeyRecordDto? key;
  final BridgeFailure? error;

  const KeyMutationResponse({this.key, this.error});

  @override
  int get hashCode => key.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyMutationResponse &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          error == other.error;
}

class KeyRecordDto {
  final String keyType;
  final String name;
  final String fingerprint;
  final String source;
  final bool hasPrivateKey;

  const KeyRecordDto({
    required this.keyType,
    required this.name,
    required this.fingerprint,
    required this.source,
    required this.hasPrivateKey,
  });

  @override
  int get hashCode =>
      keyType.hashCode ^
      name.hashCode ^
      fingerprint.hashCode ^
      source.hashCode ^
      hasPrivateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyRecordDto &&
          runtimeType == other.runtimeType &&
          keyType == other.keyType &&
          name == other.name &&
          fingerprint == other.fingerprint &&
          source == other.source &&
          hasPrivateKey == other.hasPrivateKey;
}

class ListEntriesRequest {
  final String root;
  final String? target;
  final bool recursive;

  const ListEntriesRequest({
    required this.root,
    this.target,
    required this.recursive,
  });

  @override
  int get hashCode => root.hashCode ^ target.hashCode ^ recursive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListEntriesRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          target == other.target &&
          recursive == other.recursive;
}

class ListEntriesResponse {
  final List<EntrySummaryDto> entries;
  final BridgeFailure? error;

  const ListEntriesResponse({required this.entries, this.error});

  @override
  int get hashCode => entries.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListEntriesResponse &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          error == other.error;
}

class ListKeysRequest {
  final String configPath;
  final String? pgpExecutable;
  final String? sshDir;

  const ListKeysRequest({
    required this.configPath,
    this.pgpExecutable,
    this.sshDir,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^ pgpExecutable.hashCode ^ sshDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListKeysRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          sshDir == other.sshDir;
}

class ListKeysResponse {
  final List<KeyRecordDto> keys;
  final BridgeFailure? error;

  const ListKeysResponse({required this.keys, this.error});

  @override
  int get hashCode => keys.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListKeysResponse &&
          runtimeType == other.runtimeType &&
          keys == other.keys &&
          error == other.error;
}

class LoadConfigRequest {
  final String path;

  const LoadConfigRequest({required this.path});

  @override
  int get hashCode => path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadConfigRequest &&
          runtimeType == other.runtimeType &&
          path == other.path;
}

class MoveAutofillIndexEntryRequest {
  final String indexPath;
  final String oldPath;
  final String newPath;
  final bool recursive;

  const MoveAutofillIndexEntryRequest({
    required this.indexPath,
    required this.oldPath,
    required this.newPath,
    required this.recursive,
  });

  @override
  int get hashCode =>
      indexPath.hashCode ^
      oldPath.hashCode ^
      newPath.hashCode ^
      recursive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveAutofillIndexEntryRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          oldPath == other.oldPath &&
          newPath == other.newPath &&
          recursive == other.recursive;
}

class MoveEntryRequest {
  final String root;
  final String fromPath;
  final String toPath;
  final bool overwrite;

  const MoveEntryRequest({
    required this.root,
    required this.fromPath,
    required this.toPath,
    required this.overwrite,
  });

  @override
  int get hashCode =>
      root.hashCode ^ fromPath.hashCode ^ toPath.hashCode ^ overwrite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveEntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          fromPath == other.fromPath &&
          toPath == other.toPath &&
          overwrite == other.overwrite;
}

class MutationResponse {
  final MutationResultDto? result;
  final BridgeFailure? error;

  const MutationResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MutationResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class MutationResultDto {
  final String path;

  const MutationResultDto({required this.path});

  @override
  int get hashCode => path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MutationResultDto &&
          runtimeType == other.runtimeType &&
          path == other.path;
}

class OpenExternalUrlResponse {
  final String? url;
  final BridgeFailure? error;

  const OpenExternalUrlResponse({this.url, this.error});

  @override
  int get hashCode => url.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenExternalUrlResponse &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          error == other.error;
}

class OpenGithubSshSettingsRequest {
  const OpenGithubSshSettingsRequest();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenGithubSshSettingsRequest && runtimeType == other.runtimeType;
}

class ParsedEntryFieldDto {
  final String key;
  final String label;
  final String value;

  const ParsedEntryFieldDto({
    required this.key,
    required this.label,
    required this.value,
  });

  @override
  int get hashCode => key.hashCode ^ label.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedEntryFieldDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          value == other.value;
}

class PatchAutofillIndexFavoritesRequest {
  final String indexPath;
  final List<AutofillEntryMetadataDto> entries;

  const PatchAutofillIndexFavoritesRequest({
    required this.indexPath,
    required this.entries,
  });

  @override
  int get hashCode => indexPath.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatchAutofillIndexFavoritesRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          entries == other.entries;
}

/// Why a PGP import failed, so Flutter can branch without matching on message text.
enum PgpImportFailureKind {
  unsupportedMaterial,
  kindMismatch,
  passphraseRequired,
  incorrectPassphrase,
  unsupportedProtection,
  reprotectionFailed,
  backendError,
}

class PgpKeyImportResponse {
  final PgpKeyInspectionDto? inspection;
  final KeyRecordDto? key;
  final BridgeFailure? error;

  const PgpKeyImportResponse({this.inspection, this.key, this.error});

  @override
  int get hashCode => inspection.hashCode ^ key.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgpKeyImportResponse &&
          runtimeType == other.runtimeType &&
          inspection == other.inspection &&
          key == other.key &&
          error == other.error;
}

/// What inspection found in the supplied material. Carries no key bytes.
class PgpKeyInspectionDto {
  final PgpKeyKindDto kind;
  final String fingerprint;
  final String identity;
  final bool hasPrivateKey;
  final bool requiresPassphrase;
  final bool armored;

  const PgpKeyInspectionDto({
    required this.kind,
    required this.fingerprint,
    required this.identity,
    required this.hasPrivateKey,
    required this.requiresPassphrase,
    required this.armored,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      fingerprint.hashCode ^
      identity.hashCode ^
      hasPrivateKey.hashCode ^
      requiresPassphrase.hashCode ^
      armored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgpKeyInspectionDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          fingerprint == other.fingerprint &&
          identity == other.identity &&
          hasPrivateKey == other.hasPrivateKey &&
          requiresPassphrase == other.requiresPassphrase &&
          armored == other.armored;
}

class PgpKeyInspectionResponse {
  final PgpKeyInspectionDto? inspection;
  final BridgeFailure? error;

  const PgpKeyInspectionResponse({this.inspection, this.error});

  @override
  int get hashCode => inspection.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PgpKeyInspectionResponse &&
          runtimeType == other.runtimeType &&
          inspection == other.inspection &&
          error == other.error;
}

enum PgpKeyKindDto { public, private }

class PreparePgpPrivateKeyRequest {
  final String configPath;
  final String? pgpExecutable;
  final String fingerprint;
  final String passphrase;

  const PreparePgpPrivateKeyRequest({
    required this.configPath,
    this.pgpExecutable,
    required this.fingerprint,
    required this.passphrase,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      fingerprint.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparePgpPrivateKeyRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          fingerprint == other.fingerprint &&
          passphrase == other.passphrase;
}

class PreparePgpPrivateKeyResponse {
  final String? fingerprint;
  final bool migrated;
  final BridgeFailure? error;

  const PreparePgpPrivateKeyResponse({
    this.fingerprint,
    required this.migrated,
    this.error,
  });

  @override
  int get hashCode => fingerprint.hashCode ^ migrated.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparePgpPrivateKeyResponse &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          migrated == other.migrated &&
          error == other.error;
}

class RebuildAutofillIndexRequest {
  final String indexPath;
  final String storeId;
  final String storeName;
  final String root;
  final List<AutofillEntryMetadataDto> entries;

  const RebuildAutofillIndexRequest({
    required this.indexPath,
    required this.storeId,
    required this.storeName,
    required this.root,
    required this.entries,
  });

  @override
  int get hashCode =>
      indexPath.hashCode ^
      storeId.hashCode ^
      storeName.hashCode ^
      root.hashCode ^
      entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RebuildAutofillIndexRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          storeId == other.storeId &&
          storeName == other.storeName &&
          root == other.root &&
          entries == other.entries;
}

class ReconcileAutofillIndexRequest {
  final String indexPath;
  final String storeId;
  final String storeName;
  final String root;
  final List<AutofillEntryMetadataDto> entries;

  const ReconcileAutofillIndexRequest({
    required this.indexPath,
    required this.storeId,
    required this.storeName,
    required this.root,
    required this.entries,
  });

  @override
  int get hashCode =>
      indexPath.hashCode ^
      storeId.hashCode ^
      storeName.hashCode ^
      root.hashCode ^
      entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReconcileAutofillIndexRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          storeId == other.storeId &&
          storeName == other.storeName &&
          root == other.root &&
          entries == other.entries;
}

class RemoveAutofillIndexEntryRequest {
  final String indexPath;
  final String path;
  final bool recursive;

  const RemoveAutofillIndexEntryRequest({
    required this.indexPath,
    required this.path,
    required this.recursive,
  });

  @override
  int get hashCode => indexPath.hashCode ^ path.hashCode ^ recursive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoveAutofillIndexEntryRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          path == other.path &&
          recursive == other.recursive;
}

class SaveConfigRequest {
  final String path;
  final String configToml;

  const SaveConfigRequest({required this.path, required this.configToml});

  @override
  int get hashCode => path.hashCode ^ configToml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveConfigRequest &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          configToml == other.configToml;
}

enum StoreGitModeDto { disabled, local, remote, invalid }

class StoreStatusDto {
  final String name;
  final String root;
  final bool exists;
  final bool hasGpgId;
  final List<String> pgpRecipients;
  final StoreGitModeDto gitMode;
  final bool pgpKeyMissing;
  final List<String> issues;

  const StoreStatusDto({
    required this.name,
    required this.root,
    required this.exists,
    required this.hasGpgId,
    required this.pgpRecipients,
    required this.gitMode,
    required this.pgpKeyMissing,
    required this.issues,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      root.hashCode ^
      exists.hashCode ^
      hasGpgId.hashCode ^
      pgpRecipients.hashCode ^
      gitMode.hashCode ^
      pgpKeyMissing.hashCode ^
      issues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreStatusDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          root == other.root &&
          exists == other.exists &&
          hasGpgId == other.hasGpgId &&
          pgpRecipients == other.pgpRecipients &&
          gitMode == other.gitMode &&
          pgpKeyMissing == other.pgpKeyMissing &&
          issues == other.issues;
}

class UnitResponse {
  final BridgeFailure? error;

  const UnitResponse({this.error});

  @override
  int get hashCode => error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnitResponse &&
          runtimeType == other.runtimeType &&
          error == other.error;
}

class UpsertAutofillIndexEntryRequest {
  final String indexPath;
  final AutofillEntryMetadataDto entry;

  const UpsertAutofillIndexEntryRequest({
    required this.indexPath,
    required this.entry,
  });

  @override
  int get hashCode => indexPath.hashCode ^ entry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpsertAutofillIndexEntryRequest &&
          runtimeType == other.runtimeType &&
          indexPath == other.indexPath &&
          entry == other.entry;
}
