// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_store_to_config`, `clone_store_inner`, `create_local_store_inner`, `default_ssh_dir`, `delete_local_store_inner`, `entry_ref`, `git_remote_exists`, `import_local_store_inner`, `import_pgp_key_text`, `imported_key_kind`, `inspect_app_state_inner`, `inspect_store`, `list_keys_inner`, `list_stores_inner`, `load_config_for_mutation`, `normalize_store_root`, `normalized_keys`, `onboarding_state`, `pgp_backend`, `pgp_key_missing`, `read_entry_inner`, `remove_store_inner`, `run_git_command_response`, `run_git`, `save_config_for_mutation`, `select_store_inner`, `simple`, `store_failure`, `store_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Future<ConfigResponse> loadConfig({required LoadConfigRequest request}) =>
    RustLib.instance.api.crateApiLoadConfig(request: request);

Future<UnitResponse> saveConfig({required SaveConfigRequest request}) =>
    RustLib.instance.api.crateApiSaveConfig(request: request);

Future<ListStoresResponse> listStores({required ListStoresRequest request}) =>
    RustLib.instance.api.crateApiListStores(request: request);

Future<ListEntriesResponse> listEntries({
  required ListEntriesRequest request,
}) => RustLib.instance.api.crateApiListEntries(request: request);

Future<EntrySecretResponse> readEntry({required EntryRequest request}) =>
    RustLib.instance.api.crateApiReadEntry(request: request);

Future<CopyEntryPasswordResponse> copyEntryPassword({
  required EntryRequest request,
}) => RustLib.instance.api.crateApiCopyEntryPassword(request: request);

Future<InsertEntryResponse> insertEntry({
  required InsertEntryRequest request,
}) => RustLib.instance.api.crateApiInsertEntry(request: request);

Future<GenerateEntryResponse> generateEntry({
  required GenerateEntryRequest request,
}) => RustLib.instance.api.crateApiGenerateEntry(request: request);

Future<MutationResponse> editEntry({required EditEntryRequest request}) =>
    RustLib.instance.api.crateApiEditEntry(request: request);

Future<MutationResponse> moveEntry({required MoveEntryRequest request}) =>
    RustLib.instance.api.crateApiMoveEntry(request: request);

Future<DeleteEntryResponse> deleteEntry({
  required DeleteEntryRequest request,
}) => RustLib.instance.api.crateApiDeleteEntry(request: request);

Future<GitCommandResponse> gitStatus({required GitRequest request}) =>
    RustLib.instance.api.crateApiGitStatus(request: request);

Future<GitCommandResponse> gitPull({required GitRequest request}) =>
    RustLib.instance.api.crateApiGitPull(request: request);

Future<GitCommandResponse> gitPush({required GitRequest request}) =>
    RustLib.instance.api.crateApiGitPush(request: request);

Future<GitCommandResponse> gitCommit({required GitCommitRequest request}) =>
    RustLib.instance.api.crateApiGitCommit(request: request);

Future<GitCommandResponse> runGitArgs({required GitArgsRequest request}) =>
    RustLib.instance.api.crateApiRunGitArgs(request: request);

Future<AppStateResponse> inspectAppState({
  required InspectAppStateRequest request,
}) => RustLib.instance.api.crateApiInspectAppState(request: request);

Future<UnitResponse> selectStore({required SelectStoreRequest request}) =>
    RustLib.instance.api.crateApiSelectStore(request: request);

Future<UnitResponse> createLocalStore({
  required CreateLocalStoreRequest request,
}) => RustLib.instance.api.crateApiCreateLocalStore(request: request);

Future<UnitResponse> importLocalStore({
  required ImportLocalStoreRequest request,
}) => RustLib.instance.api.crateApiImportLocalStore(request: request);

Future<UnitResponse> cloneStore({required CloneStoreRequest request}) =>
    RustLib.instance.api.crateApiCloneStore(request: request);

Future<UnitResponse> removeStore({required RemoveStoreRequest request}) =>
    RustLib.instance.api.crateApiRemoveStore(request: request);

Future<UnitResponse> deleteLocalStore({
  required DeleteLocalStoreRequest request,
}) => RustLib.instance.api.crateApiDeleteLocalStore(request: request);

Future<ListKeysResponse> listKeys({required ListKeysRequest request}) =>
    RustLib.instance.api.crateApiListKeys(request: request);

Future<KeyDetectionResponse> detectImportedKey({
  required ImportKeyTextRequest request,
}) => RustLib.instance.api.crateApiDetectImportedKey(request: request);

Future<KeyMutationResponse> generatePgpKey({
  required GeneratePgpKeyRequest request,
}) => RustLib.instance.api.crateApiGeneratePgpKey(request: request);

Future<KeyMutationResponse> importPgpPublicKey({
  required ImportKeyTextRequest request,
}) => RustLib.instance.api.crateApiImportPgpPublicKey(request: request);

Future<KeyMutationResponse> importPgpPrivateKeyText({
  required ImportKeyTextRequest request,
}) => RustLib.instance.api.crateApiImportPgpPrivateKeyText(request: request);

Future<KeyMutationResponse> importPgpPrivateKeyFile({
  required ImportKeyFileRequest request,
}) => RustLib.instance.api.crateApiImportPgpPrivateKeyFile(request: request);

Future<KeyExportResponse> exportPgpPublicKey({
  required ExportPgpKeyRequest request,
}) => RustLib.instance.api.crateApiExportPgpPublicKey(request: request);

Future<KeyExportResponse> exportPgpPrivateKey({
  required ExportPgpKeyRequest request,
}) => RustLib.instance.api.crateApiExportPgpPrivateKey(request: request);

Future<UnitResponse> addPgpKeyToGpgId({
  required AddPgpKeyToGpgIdRequest request,
}) => RustLib.instance.api.crateApiAddPgpKeyToGpgId(request: request);

Future<KeyMutationResponse> generateSshKey({
  required GenerateSshKeyRequest request,
}) => RustLib.instance.api.crateApiGenerateSshKey(request: request);

Future<KeyMutationResponse> importSshPrivateKeyText({
  required ImportKeyTextRequest request,
}) => RustLib.instance.api.crateApiImportSshPrivateKeyText(request: request);

Future<KeyMutationResponse> importSshPrivateKeyFile({
  required ImportKeyFileRequest request,
}) => RustLib.instance.api.crateApiImportSshPrivateKeyFile(request: request);

Future<KeyExportResponse> exportSshPublicKey({
  required ExportSshKeyRequest request,
}) => RustLib.instance.api.crateApiExportSshPublicKey(request: request);

Future<KeyExportResponse> exportSshPrivateKey({
  required ExportSshKeyRequest request,
}) => RustLib.instance.api.crateApiExportSshPrivateKey(request: request);

Future<OpenExternalUrlResponse> openGithubSshSettings({
  required OpenGithubSshSettingsRequest request,
}) => RustLib.instance.api.crateApiOpenGithubSshSettings(request: request);

class AddPgpKeyToGpgIdRequest {
  final String root;
  final String fingerprint;

  const AddPgpKeyToGpgIdRequest({
    required this.root,
    required this.fingerprint,
  });

  @override
  int get hashCode => root.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddPgpKeyToGpgIdRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          fingerprint == other.fingerprint;
}

class AppStateDto {
  final String configPath;
  final bool configExists;
  final String? selectedStoreId;
  final String? selectedStoreRoot;
  final String onboardingState;
  final List<String> issues;
  final List<StoreStatusDto> stores;

  const AppStateDto({
    required this.configPath,
    required this.configExists,
    this.selectedStoreId,
    this.selectedStoreRoot,
    required this.onboardingState,
    required this.issues,
    required this.stores,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      configExists.hashCode ^
      selectedStoreId.hashCode ^
      selectedStoreRoot.hashCode ^
      onboardingState.hashCode ^
      issues.hashCode ^
      stores.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStateDto &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          configExists == other.configExists &&
          selectedStoreId == other.selectedStoreId &&
          selectedStoreRoot == other.selectedStoreRoot &&
          onboardingState == other.onboardingState &&
          issues == other.issues &&
          stores == other.stores;
}

class AppStateResponse {
  final AppStateDto? state;
  final BridgeFailure? error;

  const AppStateResponse({this.state, this.error});

  @override
  int get hashCode => state.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStateResponse &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          error == other.error;
}

class BridgeFailure {
  final BridgeFailureCategory category;
  final String message;
  final String? conflictKind;
  final String? path;

  const BridgeFailure({
    required this.category,
    required this.message,
    this.conflictKind,
    this.path,
  });

  @override
  int get hashCode =>
      category.hashCode ^
      message.hashCode ^
      conflictKind.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFailure &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          message == other.message &&
          conflictKind == other.conflictKind &&
          path == other.path;
}

enum BridgeFailureCategory {
  configError,
  storeError,
  pgpError,
  gitError,
  clipboardError,
  validationError,
  conflict,
  unsupportedPlatform,
}

class CloneStoreRequest {
  final String configPath;
  final String remoteUrl;
  final String root;
  final bool setDefault;

  const CloneStoreRequest({
    required this.configPath,
    required this.remoteUrl,
    required this.root,
    required this.setDefault,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      remoteUrl.hashCode ^
      root.hashCode ^
      setDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloneStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          remoteUrl == other.remoteUrl &&
          root == other.root &&
          setDefault == other.setDefault;
}

class ConfigResponse {
  final String? configToml;
  final BridgeFailure? error;

  const ConfigResponse({this.configToml, this.error});

  @override
  int get hashCode => configToml.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigResponse &&
          runtimeType == other.runtimeType &&
          configToml == other.configToml &&
          error == other.error;
}

class CopyEntryPasswordResponse {
  final CopyEntryPasswordResult? result;
  final BridgeFailure? error;

  const CopyEntryPasswordResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopyEntryPasswordResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class CopyEntryPasswordResult {
  final String path;
  final String password;

  const CopyEntryPasswordResult({required this.path, required this.password});

  @override
  int get hashCode => path.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CopyEntryPasswordResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          password == other.password;
}

class CreateLocalStoreRequest {
  final String configPath;
  final String name;
  final String root;
  final List<String> pgpKeys;
  final bool setDefault;
  final bool initializeGit;

  const CreateLocalStoreRequest({
    required this.configPath,
    required this.name,
    required this.root,
    required this.pgpKeys,
    required this.setDefault,
    required this.initializeGit,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      name.hashCode ^
      root.hashCode ^
      pgpKeys.hashCode ^
      setDefault.hashCode ^
      initializeGit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateLocalStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          name == other.name &&
          root == other.root &&
          pgpKeys == other.pgpKeys &&
          setDefault == other.setDefault &&
          initializeGit == other.initializeGit;
}

class DeleteEntryRequest {
  final String root;
  final String path;
  final bool recursive;

  const DeleteEntryRequest({
    required this.root,
    required this.path,
    required this.recursive,
  });

  @override
  int get hashCode => root.hashCode ^ path.hashCode ^ recursive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteEntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          path == other.path &&
          recursive == other.recursive;
}

class DeleteEntryResponse {
  final DeleteEntryResultDto? result;
  final BridgeFailure? error;

  const DeleteEntryResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteEntryResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class DeleteEntryResultDto {
  final String deletedPath;
  final String deletedType;

  const DeleteEntryResultDto({
    required this.deletedPath,
    required this.deletedType,
  });

  @override
  int get hashCode => deletedPath.hashCode ^ deletedType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteEntryResultDto &&
          runtimeType == other.runtimeType &&
          deletedPath == other.deletedPath &&
          deletedType == other.deletedType;
}

class DeleteLocalStoreRequest {
  final String configPath;
  final String root;
  final String confirmation;

  const DeleteLocalStoreRequest({
    required this.configPath,
    required this.root,
    required this.confirmation,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^ root.hashCode ^ confirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteLocalStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          confirmation == other.confirmation;
}

class EditEntryRequest {
  final String root;
  final String path;
  final String content;
  final String pgpExecutable;

  const EditEntryRequest({
    required this.root,
    required this.path,
    required this.content,
    required this.pgpExecutable,
  });

  @override
  int get hashCode =>
      root.hashCode ^ path.hashCode ^ content.hashCode ^ pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditEntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          path == other.path &&
          content == other.content &&
          pgpExecutable == other.pgpExecutable;
}

class EntryRequest {
  final String root;
  final String path;
  final String? pgpExecutable;

  const EntryRequest({
    required this.root,
    required this.path,
    this.pgpExecutable,
  });

  @override
  int get hashCode => root.hashCode ^ path.hashCode ^ pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          path == other.path &&
          pgpExecutable == other.pgpExecutable;
}

class EntrySecretDto {
  final String password;
  final List<ParsedEntryFieldDto> fields;
  final String rawNotes;

  const EntrySecretDto({
    required this.password,
    required this.fields,
    required this.rawNotes,
  });

  @override
  int get hashCode => password.hashCode ^ fields.hashCode ^ rawNotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySecretDto &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          fields == other.fields &&
          rawNotes == other.rawNotes;
}

class EntrySecretResponse {
  final EntrySecretDto? secret;
  final BridgeFailure? error;

  const EntrySecretResponse({this.secret, this.error});

  @override
  int get hashCode => secret.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySecretResponse &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          error == other.error;
}

class EntrySummaryDto {
  final String path;
  final String name;
  final String? parentPath;
  final String entryType;
  final int childCount;

  const EntrySummaryDto({
    required this.path,
    required this.name,
    this.parentPath,
    required this.entryType,
    required this.childCount,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      parentPath.hashCode ^
      entryType.hashCode ^
      childCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntrySummaryDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          parentPath == other.parentPath &&
          entryType == other.entryType &&
          childCount == other.childCount;
}

class ExportPgpKeyRequest {
  final String configPath;
  final String? pgpExecutable;
  final String fingerprint;
  final String? confirmation;

  const ExportPgpKeyRequest({
    required this.configPath,
    this.pgpExecutable,
    required this.fingerprint,
    this.confirmation,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      fingerprint.hashCode ^
      confirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportPgpKeyRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          fingerprint == other.fingerprint &&
          confirmation == other.confirmation;
}

class ExportSshKeyRequest {
  final String sshDir;
  final String name;
  final String? confirmation;

  const ExportSshKeyRequest({
    required this.sshDir,
    required this.name,
    this.confirmation,
  });

  @override
  int get hashCode => sshDir.hashCode ^ name.hashCode ^ confirmation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportSshKeyRequest &&
          runtimeType == other.runtimeType &&
          sshDir == other.sshDir &&
          name == other.name &&
          confirmation == other.confirmation;
}

class GenerateEntryRequest {
  final String root;
  final String path;
  final int length;
  final bool noSymbols;
  final bool overwrite;
  final String pgpExecutable;

  const GenerateEntryRequest({
    required this.root,
    required this.path,
    required this.length,
    required this.noSymbols,
    required this.overwrite,
    required this.pgpExecutable,
  });

  @override
  int get hashCode =>
      root.hashCode ^
      path.hashCode ^
      length.hashCode ^
      noSymbols.hashCode ^
      overwrite.hashCode ^
      pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateEntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          path == other.path &&
          length == other.length &&
          noSymbols == other.noSymbols &&
          overwrite == other.overwrite &&
          pgpExecutable == other.pgpExecutable;
}

class GenerateEntryResponse {
  final GenerateEntryResultDto? result;
  final BridgeFailure? error;

  const GenerateEntryResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateEntryResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class GenerateEntryResultDto {
  final String entryPath;
  final String password;
  final bool overwroteExisting;

  const GenerateEntryResultDto({
    required this.entryPath,
    required this.password,
    required this.overwroteExisting,
  });

  @override
  int get hashCode =>
      entryPath.hashCode ^ password.hashCode ^ overwroteExisting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateEntryResultDto &&
          runtimeType == other.runtimeType &&
          entryPath == other.entryPath &&
          password == other.password &&
          overwroteExisting == other.overwroteExisting;
}

class GeneratePgpKeyRequest {
  final String configPath;
  final String? pgpExecutable;
  final String name;
  final String email;
  final String? passphrase;

  const GeneratePgpKeyRequest({
    required this.configPath,
    this.pgpExecutable,
    required this.name,
    required this.email,
    this.passphrase,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      pgpExecutable.hashCode ^
      name.hashCode ^
      email.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratePgpKeyRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          name == other.name &&
          email == other.email &&
          passphrase == other.passphrase;
}

class GenerateSshKeyRequest {
  final String sshDir;
  final String name;

  const GenerateSshKeyRequest({required this.sshDir, required this.name});

  @override
  int get hashCode => sshDir.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateSshKeyRequest &&
          runtimeType == other.runtimeType &&
          sshDir == other.sshDir &&
          name == other.name;
}

class GitArgsRequest {
  final String root;
  final List<String> args;

  const GitArgsRequest({required this.root, required this.args});

  @override
  int get hashCode => root.hashCode ^ args.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitArgsRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          args == other.args;
}

class GitCommandOutputDto {
  final String command;
  final String stdout;
  final String stderr;
  final int? exitCode;
  final bool success;

  const GitCommandOutputDto({
    required this.command,
    required this.stdout,
    required this.stderr,
    this.exitCode,
    required this.success,
  });

  @override
  int get hashCode =>
      command.hashCode ^
      stdout.hashCode ^
      stderr.hashCode ^
      exitCode.hashCode ^
      success.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommandOutputDto &&
          runtimeType == other.runtimeType &&
          command == other.command &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          exitCode == other.exitCode &&
          success == other.success;
}

class GitCommandResponse {
  final GitCommandOutputDto? output;
  final BridgeFailure? error;

  const GitCommandResponse({this.output, this.error});

  @override
  int get hashCode => output.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommandResponse &&
          runtimeType == other.runtimeType &&
          output == other.output &&
          error == other.error;
}

class GitCommitRequest {
  final String root;
  final String message;

  const GitCommitRequest({required this.root, required this.message});

  @override
  int get hashCode => root.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommitRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          message == other.message;
}

class GitRequest {
  final String root;

  const GitRequest({required this.root});

  @override
  int get hashCode => root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitRequest &&
          runtimeType == other.runtimeType &&
          root == other.root;
}

class ImportKeyFileRequest {
  final String configPath;
  final String? sshDir;
  final String? name;
  final String path;

  const ImportKeyFileRequest({
    required this.configPath,
    this.sshDir,
    this.name,
    required this.path,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^ sshDir.hashCode ^ name.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportKeyFileRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          sshDir == other.sshDir &&
          name == other.name &&
          path == other.path;
}

class ImportKeyTextRequest {
  final String configPath;
  final String? sshDir;
  final String? name;
  final String armoredText;

  const ImportKeyTextRequest({
    required this.configPath,
    this.sshDir,
    this.name,
    required this.armoredText,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^
      sshDir.hashCode ^
      name.hashCode ^
      armoredText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportKeyTextRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          sshDir == other.sshDir &&
          name == other.name &&
          armoredText == other.armoredText;
}

class ImportLocalStoreRequest {
  final String configPath;
  final String root;
  final bool setDefault;

  const ImportLocalStoreRequest({
    required this.configPath,
    required this.root,
    required this.setDefault,
  });

  @override
  int get hashCode => configPath.hashCode ^ root.hashCode ^ setDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportLocalStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root &&
          setDefault == other.setDefault;
}

class InsertEntryRequest {
  final String root;
  final String path;
  final String content;
  final bool overwrite;
  final String pgpExecutable;

  const InsertEntryRequest({
    required this.root,
    required this.path,
    required this.content,
    required this.overwrite,
    required this.pgpExecutable,
  });

  @override
  int get hashCode =>
      root.hashCode ^
      path.hashCode ^
      content.hashCode ^
      overwrite.hashCode ^
      pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertEntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          path == other.path &&
          content == other.content &&
          overwrite == other.overwrite &&
          pgpExecutable == other.pgpExecutable;
}

class InsertEntryResponse {
  final InsertEntryResultDto? result;
  final BridgeFailure? error;

  const InsertEntryResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertEntryResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class InsertEntryResultDto {
  final String entryPath;
  final bool overwroteExisting;

  const InsertEntryResultDto({
    required this.entryPath,
    required this.overwroteExisting,
  });

  @override
  int get hashCode => entryPath.hashCode ^ overwroteExisting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InsertEntryResultDto &&
          runtimeType == other.runtimeType &&
          entryPath == other.entryPath &&
          overwroteExisting == other.overwroteExisting;
}

class InspectAppStateRequest {
  final String configPath;
  final String? pgpExecutable;

  const InspectAppStateRequest({required this.configPath, this.pgpExecutable});

  @override
  int get hashCode => configPath.hashCode ^ pgpExecutable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InspectAppStateRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable;
}

class KeyDetectionResponse {
  final String? kind;
  final BridgeFailure? error;

  const KeyDetectionResponse({this.kind, this.error});

  @override
  int get hashCode => kind.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyDetectionResponse &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          error == other.error;
}

class KeyExportDto {
  final String armoredText;

  const KeyExportDto({required this.armoredText});

  @override
  int get hashCode => armoredText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyExportDto &&
          runtimeType == other.runtimeType &&
          armoredText == other.armoredText;
}

class KeyExportResponse {
  final KeyExportDto? export_;
  final BridgeFailure? error;

  const KeyExportResponse({this.export_, this.error});

  @override
  int get hashCode => export_.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyExportResponse &&
          runtimeType == other.runtimeType &&
          export_ == other.export_ &&
          error == other.error;
}

class KeyMutationResponse {
  final KeyRecordDto? key;
  final BridgeFailure? error;

  const KeyMutationResponse({this.key, this.error});

  @override
  int get hashCode => key.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyMutationResponse &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          error == other.error;
}

class KeyRecordDto {
  final String keyType;
  final String name;
  final String fingerprint;
  final String source;
  final bool hasPrivateKey;

  const KeyRecordDto({
    required this.keyType,
    required this.name,
    required this.fingerprint,
    required this.source,
    required this.hasPrivateKey,
  });

  @override
  int get hashCode =>
      keyType.hashCode ^
      name.hashCode ^
      fingerprint.hashCode ^
      source.hashCode ^
      hasPrivateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyRecordDto &&
          runtimeType == other.runtimeType &&
          keyType == other.keyType &&
          name == other.name &&
          fingerprint == other.fingerprint &&
          source == other.source &&
          hasPrivateKey == other.hasPrivateKey;
}

class ListEntriesRequest {
  final String root;
  final String? target;
  final bool recursive;

  const ListEntriesRequest({
    required this.root,
    this.target,
    required this.recursive,
  });

  @override
  int get hashCode => root.hashCode ^ target.hashCode ^ recursive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListEntriesRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          target == other.target &&
          recursive == other.recursive;
}

class ListEntriesResponse {
  final List<EntrySummaryDto> entries;
  final BridgeFailure? error;

  const ListEntriesResponse({required this.entries, this.error});

  @override
  int get hashCode => entries.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListEntriesResponse &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          error == other.error;
}

class ListKeysRequest {
  final String configPath;
  final String? pgpExecutable;
  final String? sshDir;

  const ListKeysRequest({
    required this.configPath,
    this.pgpExecutable,
    this.sshDir,
  });

  @override
  int get hashCode =>
      configPath.hashCode ^ pgpExecutable.hashCode ^ sshDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListKeysRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          pgpExecutable == other.pgpExecutable &&
          sshDir == other.sshDir;
}

class ListKeysResponse {
  final List<KeyRecordDto> keys;
  final BridgeFailure? error;

  const ListKeysResponse({required this.keys, this.error});

  @override
  int get hashCode => keys.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListKeysResponse &&
          runtimeType == other.runtimeType &&
          keys == other.keys &&
          error == other.error;
}

class ListStoresRequest {
  final String? configPath;

  const ListStoresRequest({this.configPath});

  @override
  int get hashCode => configPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListStoresRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath;
}

class ListStoresResponse {
  final List<StoreInfoDto> stores;
  final BridgeFailure? error;

  const ListStoresResponse({required this.stores, this.error});

  @override
  int get hashCode => stores.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListStoresResponse &&
          runtimeType == other.runtimeType &&
          stores == other.stores &&
          error == other.error;
}

class LoadConfigRequest {
  final String path;

  const LoadConfigRequest({required this.path});

  @override
  int get hashCode => path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadConfigRequest &&
          runtimeType == other.runtimeType &&
          path == other.path;
}

class MoveEntryRequest {
  final String root;
  final String fromPath;
  final String toPath;
  final bool overwrite;

  const MoveEntryRequest({
    required this.root,
    required this.fromPath,
    required this.toPath,
    required this.overwrite,
  });

  @override
  int get hashCode =>
      root.hashCode ^ fromPath.hashCode ^ toPath.hashCode ^ overwrite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MoveEntryRequest &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          fromPath == other.fromPath &&
          toPath == other.toPath &&
          overwrite == other.overwrite;
}

class MutationResponse {
  final MutationResultDto? result;
  final BridgeFailure? error;

  const MutationResponse({this.result, this.error});

  @override
  int get hashCode => result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MutationResponse &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          error == other.error;
}

class MutationResultDto {
  final String path;

  const MutationResultDto({required this.path});

  @override
  int get hashCode => path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MutationResultDto &&
          runtimeType == other.runtimeType &&
          path == other.path;
}

class OpenExternalUrlResponse {
  final String? url;
  final BridgeFailure? error;

  const OpenExternalUrlResponse({this.url, this.error});

  @override
  int get hashCode => url.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenExternalUrlResponse &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          error == other.error;
}

class OpenGithubSshSettingsRequest {
  const OpenGithubSshSettingsRequest();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenGithubSshSettingsRequest && runtimeType == other.runtimeType;
}

class ParsedEntryFieldDto {
  final String key;
  final String label;
  final String value;

  const ParsedEntryFieldDto({
    required this.key,
    required this.label,
    required this.value,
  });

  @override
  int get hashCode => key.hashCode ^ label.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedEntryFieldDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          value == other.value;
}

class RemoveStoreRequest {
  final String configPath;
  final String root;

  const RemoveStoreRequest({required this.configPath, required this.root});

  @override
  int get hashCode => configPath.hashCode ^ root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoveStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root;
}

class SaveConfigRequest {
  final String path;
  final String configToml;

  const SaveConfigRequest({required this.path, required this.configToml});

  @override
  int get hashCode => path.hashCode ^ configToml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveConfigRequest &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          configToml == other.configToml;
}

class SelectStoreRequest {
  final String configPath;
  final String root;

  const SelectStoreRequest({required this.configPath, required this.root});

  @override
  int get hashCode => configPath.hashCode ^ root.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelectStoreRequest &&
          runtimeType == other.runtimeType &&
          configPath == other.configPath &&
          root == other.root;
}

class StoreInfoDto {
  final String id;
  final String name;
  final String root;
  final bool isDefault;

  const StoreInfoDto({
    required this.id,
    required this.name,
    required this.root,
    required this.isDefault,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ root.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          root == other.root &&
          isDefault == other.isDefault;
}

class StoreStatusDto {
  final String id;
  final String name;
  final String root;
  final bool isDefault;
  final bool exists;
  final bool hasGpgId;
  final bool hasGitRemote;
  final bool pgpKeyMissing;
  final List<String> issues;

  const StoreStatusDto({
    required this.id,
    required this.name,
    required this.root,
    required this.isDefault,
    required this.exists,
    required this.hasGpgId,
    required this.hasGitRemote,
    required this.pgpKeyMissing,
    required this.issues,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      root.hashCode ^
      isDefault.hashCode ^
      exists.hashCode ^
      hasGpgId.hashCode ^
      hasGitRemote.hashCode ^
      pgpKeyMissing.hashCode ^
      issues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreStatusDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          root == other.root &&
          isDefault == other.isDefault &&
          exists == other.exists &&
          hasGpgId == other.hasGpgId &&
          hasGitRemote == other.hasGitRemote &&
          pgpKeyMissing == other.pgpKeyMissing &&
          issues == other.issues;
}

class UnitResponse {
  final BridgeFailure? error;

  const UnitResponse({this.error});

  @override
  int get hashCode => error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnitResponse &&
          runtimeType == other.runtimeType &&
          error == other.error;
}
