// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddPgpKeyToGpgIdRequest dco_decode_add_pgp_key_to_gpg_id_request(dynamic raw);

  @protected
  AppStateDto dco_decode_app_state_dto(dynamic raw);

  @protected
  AppStateResponse dco_decode_app_state_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AddPgpKeyToGpgIdRequest dco_decode_box_autoadd_add_pgp_key_to_gpg_id_request(
    dynamic raw,
  );

  @protected
  AppStateDto dco_decode_box_autoadd_app_state_dto(dynamic raw);

  @protected
  BridgeFailure dco_decode_box_autoadd_bridge_failure(dynamic raw);

  @protected
  CloneStoreRequest dco_decode_box_autoadd_clone_store_request(dynamic raw);

  @protected
  ConfigurePgpBackendRequest
  dco_decode_box_autoadd_configure_pgp_backend_request(dynamic raw);

  @protected
  CopyEntryPasswordResult dco_decode_box_autoadd_copy_entry_password_result(
    dynamic raw,
  );

  @protected
  CreateLocalStoreRequest dco_decode_box_autoadd_create_local_store_request(
    dynamic raw,
  );

  @protected
  DeleteEntryRequest dco_decode_box_autoadd_delete_entry_request(dynamic raw);

  @protected
  DeleteEntryResultDto dco_decode_box_autoadd_delete_entry_result_dto(
    dynamic raw,
  );

  @protected
  DeleteLocalStoreRequest dco_decode_box_autoadd_delete_local_store_request(
    dynamic raw,
  );

  @protected
  DeletePgpKeyRequest dco_decode_box_autoadd_delete_pgp_key_request(
    dynamic raw,
  );

  @protected
  DeleteSshKeyRequest dco_decode_box_autoadd_delete_ssh_key_request(
    dynamic raw,
  );

  @protected
  EditEntryRequest dco_decode_box_autoadd_edit_entry_request(dynamic raw);

  @protected
  EntryRequest dco_decode_box_autoadd_entry_request(dynamic raw);

  @protected
  EntrySecretDto dco_decode_box_autoadd_entry_secret_dto(dynamic raw);

  @protected
  ExportPgpKeyRequest dco_decode_box_autoadd_export_pgp_key_request(
    dynamic raw,
  );

  @protected
  ExportSshKeyRequest dco_decode_box_autoadd_export_ssh_key_request(
    dynamic raw,
  );

  @protected
  GenerateEntryRequest dco_decode_box_autoadd_generate_entry_request(
    dynamic raw,
  );

  @protected
  GenerateEntryResultDto dco_decode_box_autoadd_generate_entry_result_dto(
    dynamic raw,
  );

  @protected
  GeneratePgpKeyRequest dco_decode_box_autoadd_generate_pgp_key_request(
    dynamic raw,
  );

  @protected
  GenerateSshKeyRequest dco_decode_box_autoadd_generate_ssh_key_request(
    dynamic raw,
  );

  @protected
  GitArgsRequest dco_decode_box_autoadd_git_args_request(dynamic raw);

  @protected
  GitCommandOutputDto dco_decode_box_autoadd_git_command_output_dto(
    dynamic raw,
  );

  @protected
  GitCommitRequest dco_decode_box_autoadd_git_commit_request(dynamic raw);

  @protected
  GitRequest dco_decode_box_autoadd_git_request(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  ImportKeyFileRequest dco_decode_box_autoadd_import_key_file_request(
    dynamic raw,
  );

  @protected
  ImportKeyTextRequest dco_decode_box_autoadd_import_key_text_request(
    dynamic raw,
  );

  @protected
  ImportLocalStoreRequest dco_decode_box_autoadd_import_local_store_request(
    dynamic raw,
  );

  @protected
  InsertEntryRequest dco_decode_box_autoadd_insert_entry_request(dynamic raw);

  @protected
  InsertEntryResultDto dco_decode_box_autoadd_insert_entry_result_dto(
    dynamic raw,
  );

  @protected
  InspectAppStateRequest dco_decode_box_autoadd_inspect_app_state_request(
    dynamic raw,
  );

  @protected
  KeyExportDto dco_decode_box_autoadd_key_export_dto(dynamic raw);

  @protected
  KeyRecordDto dco_decode_box_autoadd_key_record_dto(dynamic raw);

  @protected
  ListEntriesRequest dco_decode_box_autoadd_list_entries_request(dynamic raw);

  @protected
  ListKeysRequest dco_decode_box_autoadd_list_keys_request(dynamic raw);

  @protected
  ListStoresRequest dco_decode_box_autoadd_list_stores_request(dynamic raw);

  @protected
  LoadConfigRequest dco_decode_box_autoadd_load_config_request(dynamic raw);

  @protected
  MoveEntryRequest dco_decode_box_autoadd_move_entry_request(dynamic raw);

  @protected
  MutationResultDto dco_decode_box_autoadd_mutation_result_dto(dynamic raw);

  @protected
  OpenGithubSshSettingsRequest
  dco_decode_box_autoadd_open_github_ssh_settings_request(dynamic raw);

  @protected
  RemoveStoreRequest dco_decode_box_autoadd_remove_store_request(dynamic raw);

  @protected
  SaveConfigRequest dco_decode_box_autoadd_save_config_request(dynamic raw);

  @protected
  SelectStoreRequest dco_decode_box_autoadd_select_store_request(dynamic raw);

  @protected
  BridgeFailure dco_decode_bridge_failure(dynamic raw);

  @protected
  BridgeFailureCategory dco_decode_bridge_failure_category(dynamic raw);

  @protected
  CloneStoreRequest dco_decode_clone_store_request(dynamic raw);

  @protected
  ConfigResponse dco_decode_config_response(dynamic raw);

  @protected
  ConfigurePgpBackendRequest dco_decode_configure_pgp_backend_request(
    dynamic raw,
  );

  @protected
  CopyEntryPasswordResponse dco_decode_copy_entry_password_response(
    dynamic raw,
  );

  @protected
  CopyEntryPasswordResult dco_decode_copy_entry_password_result(dynamic raw);

  @protected
  CreateLocalStoreRequest dco_decode_create_local_store_request(dynamic raw);

  @protected
  DeleteEntryRequest dco_decode_delete_entry_request(dynamic raw);

  @protected
  DeleteEntryResponse dco_decode_delete_entry_response(dynamic raw);

  @protected
  DeleteEntryResultDto dco_decode_delete_entry_result_dto(dynamic raw);

  @protected
  DeleteLocalStoreRequest dco_decode_delete_local_store_request(dynamic raw);

  @protected
  DeletePgpKeyRequest dco_decode_delete_pgp_key_request(dynamic raw);

  @protected
  DeleteSshKeyRequest dco_decode_delete_ssh_key_request(dynamic raw);

  @protected
  EditEntryRequest dco_decode_edit_entry_request(dynamic raw);

  @protected
  EntryRequest dco_decode_entry_request(dynamic raw);

  @protected
  EntrySecretDto dco_decode_entry_secret_dto(dynamic raw);

  @protected
  EntrySecretResponse dco_decode_entry_secret_response(dynamic raw);

  @protected
  EntrySummaryDto dco_decode_entry_summary_dto(dynamic raw);

  @protected
  ExportPgpKeyRequest dco_decode_export_pgp_key_request(dynamic raw);

  @protected
  ExportSshKeyRequest dco_decode_export_ssh_key_request(dynamic raw);

  @protected
  GenerateEntryRequest dco_decode_generate_entry_request(dynamic raw);

  @protected
  GenerateEntryResponse dco_decode_generate_entry_response(dynamic raw);

  @protected
  GenerateEntryResultDto dco_decode_generate_entry_result_dto(dynamic raw);

  @protected
  GeneratePgpKeyRequest dco_decode_generate_pgp_key_request(dynamic raw);

  @protected
  GenerateSshKeyRequest dco_decode_generate_ssh_key_request(dynamic raw);

  @protected
  GitArgsRequest dco_decode_git_args_request(dynamic raw);

  @protected
  GitCommandOutputDto dco_decode_git_command_output_dto(dynamic raw);

  @protected
  GitCommandResponse dco_decode_git_command_response(dynamic raw);

  @protected
  GitCommitRequest dco_decode_git_commit_request(dynamic raw);

  @protected
  GitRequest dco_decode_git_request(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImportKeyFileRequest dco_decode_import_key_file_request(dynamic raw);

  @protected
  ImportKeyTextRequest dco_decode_import_key_text_request(dynamic raw);

  @protected
  ImportLocalStoreRequest dco_decode_import_local_store_request(dynamic raw);

  @protected
  InsertEntryRequest dco_decode_insert_entry_request(dynamic raw);

  @protected
  InsertEntryResponse dco_decode_insert_entry_response(dynamic raw);

  @protected
  InsertEntryResultDto dco_decode_insert_entry_result_dto(dynamic raw);

  @protected
  InspectAppStateRequest dco_decode_inspect_app_state_request(dynamic raw);

  @protected
  KeyDetectionResponse dco_decode_key_detection_response(dynamic raw);

  @protected
  KeyExportDto dco_decode_key_export_dto(dynamic raw);

  @protected
  KeyExportResponse dco_decode_key_export_response(dynamic raw);

  @protected
  KeyMutationResponse dco_decode_key_mutation_response(dynamic raw);

  @protected
  KeyRecordDto dco_decode_key_record_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  ListEntriesRequest dco_decode_list_entries_request(dynamic raw);

  @protected
  ListEntriesResponse dco_decode_list_entries_response(dynamic raw);

  @protected
  List<EntrySummaryDto> dco_decode_list_entry_summary_dto(dynamic raw);

  @protected
  List<KeyRecordDto> dco_decode_list_key_record_dto(dynamic raw);

  @protected
  ListKeysRequest dco_decode_list_keys_request(dynamic raw);

  @protected
  ListKeysResponse dco_decode_list_keys_response(dynamic raw);

  @protected
  List<ParsedEntryFieldDto> dco_decode_list_parsed_entry_field_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StoreInfoDto> dco_decode_list_store_info_dto(dynamic raw);

  @protected
  List<StoreStatusDto> dco_decode_list_store_status_dto(dynamic raw);

  @protected
  ListStoresRequest dco_decode_list_stores_request(dynamic raw);

  @protected
  ListStoresResponse dco_decode_list_stores_response(dynamic raw);

  @protected
  LoadConfigRequest dco_decode_load_config_request(dynamic raw);

  @protected
  MoveEntryRequest dco_decode_move_entry_request(dynamic raw);

  @protected
  MutationResponse dco_decode_mutation_response(dynamic raw);

  @protected
  MutationResultDto dco_decode_mutation_result_dto(dynamic raw);

  @protected
  OpenExternalUrlResponse dco_decode_open_external_url_response(dynamic raw);

  @protected
  OpenGithubSshSettingsRequest dco_decode_open_github_ssh_settings_request(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AppStateDto? dco_decode_opt_box_autoadd_app_state_dto(dynamic raw);

  @protected
  BridgeFailure? dco_decode_opt_box_autoadd_bridge_failure(dynamic raw);

  @protected
  CopyEntryPasswordResult?
  dco_decode_opt_box_autoadd_copy_entry_password_result(dynamic raw);

  @protected
  DeleteEntryResultDto? dco_decode_opt_box_autoadd_delete_entry_result_dto(
    dynamic raw,
  );

  @protected
  EntrySecretDto? dco_decode_opt_box_autoadd_entry_secret_dto(dynamic raw);

  @protected
  GenerateEntryResultDto? dco_decode_opt_box_autoadd_generate_entry_result_dto(
    dynamic raw,
  );

  @protected
  GitCommandOutputDto? dco_decode_opt_box_autoadd_git_command_output_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  InsertEntryResultDto? dco_decode_opt_box_autoadd_insert_entry_result_dto(
    dynamic raw,
  );

  @protected
  KeyExportDto? dco_decode_opt_box_autoadd_key_export_dto(dynamic raw);

  @protected
  KeyRecordDto? dco_decode_opt_box_autoadd_key_record_dto(dynamic raw);

  @protected
  MutationResultDto? dco_decode_opt_box_autoadd_mutation_result_dto(
    dynamic raw,
  );

  @protected
  ParsedEntryFieldDto dco_decode_parsed_entry_field_dto(dynamic raw);

  @protected
  RemoveStoreRequest dco_decode_remove_store_request(dynamic raw);

  @protected
  SaveConfigRequest dco_decode_save_config_request(dynamic raw);

  @protected
  SelectStoreRequest dco_decode_select_store_request(dynamic raw);

  @protected
  StoreInfoDto dco_decode_store_info_dto(dynamic raw);

  @protected
  StoreStatusDto dco_decode_store_status_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnitResponse dco_decode_unit_response(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddPgpKeyToGpgIdRequest sse_decode_add_pgp_key_to_gpg_id_request(
    SseDeserializer deserializer,
  );

  @protected
  AppStateDto sse_decode_app_state_dto(SseDeserializer deserializer);

  @protected
  AppStateResponse sse_decode_app_state_response(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AddPgpKeyToGpgIdRequest sse_decode_box_autoadd_add_pgp_key_to_gpg_id_request(
    SseDeserializer deserializer,
  );

  @protected
  AppStateDto sse_decode_box_autoadd_app_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeFailure sse_decode_box_autoadd_bridge_failure(
    SseDeserializer deserializer,
  );

  @protected
  CloneStoreRequest sse_decode_box_autoadd_clone_store_request(
    SseDeserializer deserializer,
  );

  @protected
  ConfigurePgpBackendRequest
  sse_decode_box_autoadd_configure_pgp_backend_request(
    SseDeserializer deserializer,
  );

  @protected
  CopyEntryPasswordResult sse_decode_box_autoadd_copy_entry_password_result(
    SseDeserializer deserializer,
  );

  @protected
  CreateLocalStoreRequest sse_decode_box_autoadd_create_local_store_request(
    SseDeserializer deserializer,
  );

  @protected
  DeleteEntryRequest sse_decode_box_autoadd_delete_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  DeleteEntryResultDto sse_decode_box_autoadd_delete_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  DeleteLocalStoreRequest sse_decode_box_autoadd_delete_local_store_request(
    SseDeserializer deserializer,
  );

  @protected
  DeletePgpKeyRequest sse_decode_box_autoadd_delete_pgp_key_request(
    SseDeserializer deserializer,
  );

  @protected
  DeleteSshKeyRequest sse_decode_box_autoadd_delete_ssh_key_request(
    SseDeserializer deserializer,
  );

  @protected
  EditEntryRequest sse_decode_box_autoadd_edit_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  EntryRequest sse_decode_box_autoadd_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  EntrySecretDto sse_decode_box_autoadd_entry_secret_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExportPgpKeyRequest sse_decode_box_autoadd_export_pgp_key_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportSshKeyRequest sse_decode_box_autoadd_export_ssh_key_request(
    SseDeserializer deserializer,
  );

  @protected
  GenerateEntryRequest sse_decode_box_autoadd_generate_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  GenerateEntryResultDto sse_decode_box_autoadd_generate_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  GeneratePgpKeyRequest sse_decode_box_autoadd_generate_pgp_key_request(
    SseDeserializer deserializer,
  );

  @protected
  GenerateSshKeyRequest sse_decode_box_autoadd_generate_ssh_key_request(
    SseDeserializer deserializer,
  );

  @protected
  GitArgsRequest sse_decode_box_autoadd_git_args_request(
    SseDeserializer deserializer,
  );

  @protected
  GitCommandOutputDto sse_decode_box_autoadd_git_command_output_dto(
    SseDeserializer deserializer,
  );

  @protected
  GitCommitRequest sse_decode_box_autoadd_git_commit_request(
    SseDeserializer deserializer,
  );

  @protected
  GitRequest sse_decode_box_autoadd_git_request(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  ImportKeyFileRequest sse_decode_box_autoadd_import_key_file_request(
    SseDeserializer deserializer,
  );

  @protected
  ImportKeyTextRequest sse_decode_box_autoadd_import_key_text_request(
    SseDeserializer deserializer,
  );

  @protected
  ImportLocalStoreRequest sse_decode_box_autoadd_import_local_store_request(
    SseDeserializer deserializer,
  );

  @protected
  InsertEntryRequest sse_decode_box_autoadd_insert_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  InsertEntryResultDto sse_decode_box_autoadd_insert_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  InspectAppStateRequest sse_decode_box_autoadd_inspect_app_state_request(
    SseDeserializer deserializer,
  );

  @protected
  KeyExportDto sse_decode_box_autoadd_key_export_dto(
    SseDeserializer deserializer,
  );

  @protected
  KeyRecordDto sse_decode_box_autoadd_key_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  ListEntriesRequest sse_decode_box_autoadd_list_entries_request(
    SseDeserializer deserializer,
  );

  @protected
  ListKeysRequest sse_decode_box_autoadd_list_keys_request(
    SseDeserializer deserializer,
  );

  @protected
  ListStoresRequest sse_decode_box_autoadd_list_stores_request(
    SseDeserializer deserializer,
  );

  @protected
  LoadConfigRequest sse_decode_box_autoadd_load_config_request(
    SseDeserializer deserializer,
  );

  @protected
  MoveEntryRequest sse_decode_box_autoadd_move_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  MutationResultDto sse_decode_box_autoadd_mutation_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  OpenGithubSshSettingsRequest
  sse_decode_box_autoadd_open_github_ssh_settings_request(
    SseDeserializer deserializer,
  );

  @protected
  RemoveStoreRequest sse_decode_box_autoadd_remove_store_request(
    SseDeserializer deserializer,
  );

  @protected
  SaveConfigRequest sse_decode_box_autoadd_save_config_request(
    SseDeserializer deserializer,
  );

  @protected
  SelectStoreRequest sse_decode_box_autoadd_select_store_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeFailure sse_decode_bridge_failure(SseDeserializer deserializer);

  @protected
  BridgeFailureCategory sse_decode_bridge_failure_category(
    SseDeserializer deserializer,
  );

  @protected
  CloneStoreRequest sse_decode_clone_store_request(
    SseDeserializer deserializer,
  );

  @protected
  ConfigResponse sse_decode_config_response(SseDeserializer deserializer);

  @protected
  ConfigurePgpBackendRequest sse_decode_configure_pgp_backend_request(
    SseDeserializer deserializer,
  );

  @protected
  CopyEntryPasswordResponse sse_decode_copy_entry_password_response(
    SseDeserializer deserializer,
  );

  @protected
  CopyEntryPasswordResult sse_decode_copy_entry_password_result(
    SseDeserializer deserializer,
  );

  @protected
  CreateLocalStoreRequest sse_decode_create_local_store_request(
    SseDeserializer deserializer,
  );

  @protected
  DeleteEntryRequest sse_decode_delete_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  DeleteEntryResponse sse_decode_delete_entry_response(
    SseDeserializer deserializer,
  );

  @protected
  DeleteEntryResultDto sse_decode_delete_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  DeleteLocalStoreRequest sse_decode_delete_local_store_request(
    SseDeserializer deserializer,
  );

  @protected
  DeletePgpKeyRequest sse_decode_delete_pgp_key_request(
    SseDeserializer deserializer,
  );

  @protected
  DeleteSshKeyRequest sse_decode_delete_ssh_key_request(
    SseDeserializer deserializer,
  );

  @protected
  EditEntryRequest sse_decode_edit_entry_request(SseDeserializer deserializer);

  @protected
  EntryRequest sse_decode_entry_request(SseDeserializer deserializer);

  @protected
  EntrySecretDto sse_decode_entry_secret_dto(SseDeserializer deserializer);

  @protected
  EntrySecretResponse sse_decode_entry_secret_response(
    SseDeserializer deserializer,
  );

  @protected
  EntrySummaryDto sse_decode_entry_summary_dto(SseDeserializer deserializer);

  @protected
  ExportPgpKeyRequest sse_decode_export_pgp_key_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportSshKeyRequest sse_decode_export_ssh_key_request(
    SseDeserializer deserializer,
  );

  @protected
  GenerateEntryRequest sse_decode_generate_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  GenerateEntryResponse sse_decode_generate_entry_response(
    SseDeserializer deserializer,
  );

  @protected
  GenerateEntryResultDto sse_decode_generate_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  GeneratePgpKeyRequest sse_decode_generate_pgp_key_request(
    SseDeserializer deserializer,
  );

  @protected
  GenerateSshKeyRequest sse_decode_generate_ssh_key_request(
    SseDeserializer deserializer,
  );

  @protected
  GitArgsRequest sse_decode_git_args_request(SseDeserializer deserializer);

  @protected
  GitCommandOutputDto sse_decode_git_command_output_dto(
    SseDeserializer deserializer,
  );

  @protected
  GitCommandResponse sse_decode_git_command_response(
    SseDeserializer deserializer,
  );

  @protected
  GitCommitRequest sse_decode_git_commit_request(SseDeserializer deserializer);

  @protected
  GitRequest sse_decode_git_request(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImportKeyFileRequest sse_decode_import_key_file_request(
    SseDeserializer deserializer,
  );

  @protected
  ImportKeyTextRequest sse_decode_import_key_text_request(
    SseDeserializer deserializer,
  );

  @protected
  ImportLocalStoreRequest sse_decode_import_local_store_request(
    SseDeserializer deserializer,
  );

  @protected
  InsertEntryRequest sse_decode_insert_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  InsertEntryResponse sse_decode_insert_entry_response(
    SseDeserializer deserializer,
  );

  @protected
  InsertEntryResultDto sse_decode_insert_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  InspectAppStateRequest sse_decode_inspect_app_state_request(
    SseDeserializer deserializer,
  );

  @protected
  KeyDetectionResponse sse_decode_key_detection_response(
    SseDeserializer deserializer,
  );

  @protected
  KeyExportDto sse_decode_key_export_dto(SseDeserializer deserializer);

  @protected
  KeyExportResponse sse_decode_key_export_response(
    SseDeserializer deserializer,
  );

  @protected
  KeyMutationResponse sse_decode_key_mutation_response(
    SseDeserializer deserializer,
  );

  @protected
  KeyRecordDto sse_decode_key_record_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  ListEntriesRequest sse_decode_list_entries_request(
    SseDeserializer deserializer,
  );

  @protected
  ListEntriesResponse sse_decode_list_entries_response(
    SseDeserializer deserializer,
  );

  @protected
  List<EntrySummaryDto> sse_decode_list_entry_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<KeyRecordDto> sse_decode_list_key_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  ListKeysRequest sse_decode_list_keys_request(SseDeserializer deserializer);

  @protected
  ListKeysResponse sse_decode_list_keys_response(SseDeserializer deserializer);

  @protected
  List<ParsedEntryFieldDto> sse_decode_list_parsed_entry_field_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StoreInfoDto> sse_decode_list_store_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<StoreStatusDto> sse_decode_list_store_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  ListStoresRequest sse_decode_list_stores_request(
    SseDeserializer deserializer,
  );

  @protected
  ListStoresResponse sse_decode_list_stores_response(
    SseDeserializer deserializer,
  );

  @protected
  LoadConfigRequest sse_decode_load_config_request(
    SseDeserializer deserializer,
  );

  @protected
  MoveEntryRequest sse_decode_move_entry_request(SseDeserializer deserializer);

  @protected
  MutationResponse sse_decode_mutation_response(SseDeserializer deserializer);

  @protected
  MutationResultDto sse_decode_mutation_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  OpenExternalUrlResponse sse_decode_open_external_url_response(
    SseDeserializer deserializer,
  );

  @protected
  OpenGithubSshSettingsRequest sse_decode_open_github_ssh_settings_request(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AppStateDto? sse_decode_opt_box_autoadd_app_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeFailure? sse_decode_opt_box_autoadd_bridge_failure(
    SseDeserializer deserializer,
  );

  @protected
  CopyEntryPasswordResult?
  sse_decode_opt_box_autoadd_copy_entry_password_result(
    SseDeserializer deserializer,
  );

  @protected
  DeleteEntryResultDto? sse_decode_opt_box_autoadd_delete_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  EntrySecretDto? sse_decode_opt_box_autoadd_entry_secret_dto(
    SseDeserializer deserializer,
  );

  @protected
  GenerateEntryResultDto? sse_decode_opt_box_autoadd_generate_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  GitCommandOutputDto? sse_decode_opt_box_autoadd_git_command_output_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  InsertEntryResultDto? sse_decode_opt_box_autoadd_insert_entry_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  KeyExportDto? sse_decode_opt_box_autoadd_key_export_dto(
    SseDeserializer deserializer,
  );

  @protected
  KeyRecordDto? sse_decode_opt_box_autoadd_key_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  MutationResultDto? sse_decode_opt_box_autoadd_mutation_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  ParsedEntryFieldDto sse_decode_parsed_entry_field_dto(
    SseDeserializer deserializer,
  );

  @protected
  RemoveStoreRequest sse_decode_remove_store_request(
    SseDeserializer deserializer,
  );

  @protected
  SaveConfigRequest sse_decode_save_config_request(
    SseDeserializer deserializer,
  );

  @protected
  SelectStoreRequest sse_decode_select_store_request(
    SseDeserializer deserializer,
  );

  @protected
  StoreInfoDto sse_decode_store_info_dto(SseDeserializer deserializer);

  @protected
  StoreStatusDto sse_decode_store_status_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnitResponse sse_decode_unit_response(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_add_pgp_key_to_gpg_id_request(
    AddPgpKeyToGpgIdRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_state_dto(AppStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_app_state_response(
    AppStateResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_add_pgp_key_to_gpg_id_request(
    AddPgpKeyToGpgIdRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_app_state_dto(
    AppStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_failure(
    BridgeFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_clone_store_request(
    CloneStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_configure_pgp_backend_request(
    ConfigurePgpBackendRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_copy_entry_password_result(
    CopyEntryPasswordResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_local_store_request(
    CreateLocalStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_entry_request(
    DeleteEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_entry_result_dto(
    DeleteEntryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_local_store_request(
    DeleteLocalStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_pgp_key_request(
    DeletePgpKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_ssh_key_request(
    DeleteSshKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_entry_request(
    EditEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_request(
    EntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_entry_secret_dto(
    EntrySecretDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_pgp_key_request(
    ExportPgpKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_ssh_key_request(
    ExportSshKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_generate_entry_request(
    GenerateEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_generate_entry_result_dto(
    GenerateEntryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_generate_pgp_key_request(
    GeneratePgpKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_generate_ssh_key_request(
    GenerateSshKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_args_request(
    GitArgsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_command_output_dto(
    GitCommandOutputDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_commit_request(
    GitCommitRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_request(
    GitRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_import_key_file_request(
    ImportKeyFileRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_key_text_request(
    ImportKeyTextRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_local_store_request(
    ImportLocalStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_insert_entry_request(
    InsertEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_insert_entry_result_dto(
    InsertEntryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_inspect_app_state_request(
    InspectAppStateRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_key_export_dto(
    KeyExportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_key_record_dto(
    KeyRecordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_entries_request(
    ListEntriesRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_keys_request(
    ListKeysRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_stores_request(
    ListStoresRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_load_config_request(
    LoadConfigRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_move_entry_request(
    MoveEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mutation_result_dto(
    MutationResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_open_github_ssh_settings_request(
    OpenGithubSshSettingsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remove_store_request(
    RemoveStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_save_config_request(
    SaveConfigRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_select_store_request(
    SelectStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_failure(BridgeFailure self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_failure_category(
    BridgeFailureCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clone_store_request(
    CloneStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_response(
    ConfigResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_configure_pgp_backend_request(
    ConfigurePgpBackendRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_copy_entry_password_response(
    CopyEntryPasswordResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_copy_entry_password_result(
    CopyEntryPasswordResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_local_store_request(
    CreateLocalStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_entry_request(
    DeleteEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_entry_response(
    DeleteEntryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_entry_result_dto(
    DeleteEntryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_local_store_request(
    DeleteLocalStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_pgp_key_request(
    DeletePgpKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_ssh_key_request(
    DeleteSshKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_entry_request(
    EditEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_request(EntryRequest self, SseSerializer serializer);

  @protected
  void sse_encode_entry_secret_dto(
    EntrySecretDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_secret_response(
    EntrySecretResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_summary_dto(
    EntrySummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_pgp_key_request(
    ExportPgpKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_ssh_key_request(
    ExportSshKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generate_entry_request(
    GenerateEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generate_entry_response(
    GenerateEntryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generate_entry_result_dto(
    GenerateEntryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generate_pgp_key_request(
    GeneratePgpKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_generate_ssh_key_request(
    GenerateSshKeyRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_args_request(
    GitArgsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_command_output_dto(
    GitCommandOutputDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_command_response(
    GitCommandResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_commit_request(
    GitCommitRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_request(GitRequest self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_import_key_file_request(
    ImportKeyFileRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_key_text_request(
    ImportKeyTextRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_local_store_request(
    ImportLocalStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_insert_entry_request(
    InsertEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_insert_entry_response(
    InsertEntryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_insert_entry_result_dto(
    InsertEntryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_inspect_app_state_request(
    InspectAppStateRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_key_detection_response(
    KeyDetectionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_key_export_dto(KeyExportDto self, SseSerializer serializer);

  @protected
  void sse_encode_key_export_response(
    KeyExportResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_key_mutation_response(
    KeyMutationResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_key_record_dto(KeyRecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entries_request(
    ListEntriesRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entries_response(
    ListEntriesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_summary_dto(
    List<EntrySummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_key_record_dto(
    List<KeyRecordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_keys_request(
    ListKeysRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_keys_response(
    ListKeysResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parsed_entry_field_dto(
    List<ParsedEntryFieldDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_store_info_dto(
    List<StoreInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_store_status_dto(
    List<StoreStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stores_request(
    ListStoresRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stores_response(
    ListStoresResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_load_config_request(
    LoadConfigRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_move_entry_request(
    MoveEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mutation_response(
    MutationResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mutation_result_dto(
    MutationResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_external_url_response(
    OpenExternalUrlResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_github_ssh_settings_request(
    OpenGithubSshSettingsRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_app_state_dto(
    AppStateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_failure(
    BridgeFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_copy_entry_password_result(
    CopyEntryPasswordResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_delete_entry_result_dto(
    DeleteEntryResultDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_entry_secret_dto(
    EntrySecretDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_generate_entry_result_dto(
    GenerateEntryResultDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_git_command_output_dto(
    GitCommandOutputDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_insert_entry_result_dto(
    InsertEntryResultDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_key_export_dto(
    KeyExportDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_key_record_dto(
    KeyRecordDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mutation_result_dto(
    MutationResultDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parsed_entry_field_dto(
    ParsedEntryFieldDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remove_store_request(
    RemoveStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_save_config_request(
    SaveConfigRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_select_store_request(
    SelectStoreRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_store_info_dto(StoreInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_store_status_dto(
    StoreStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unit_response(UnitResponse self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
