name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: clippy,rustfmt
    - name: Format check
      run: cargo fmt --all -- --check
      working-directory: ./core
      
    - name: Build core
      run: cargo build --verbose
      working-directory: ./core

    - name: Run core tests
      run: cargo test --verbose
      working-directory: ./core
